#ifndef MBEDTLS_CONFIG_THREAD_H
#define MBEDTLS_CONFIG_THREAD_H

#if 1 //use sdk default mbedtls config, add openthread need
//#include "mbedtls/mbedtls_config.h" //has include in config.h
#include "mbedtls/build_info.h"

#ifndef OPENTHREAD_CONFIG_CORE_USER_CONFIG_HEADER_ENABLE
#define OPENTHREAD_CONFIG_CORE_USER_CONFIG_HEADER_ENABLE
#endif

#include "openthread-core-config.h"

#include <openthread/config.h>

#ifndef MBEDTLS_PLATFORM_SNPRINTF_MACRO
#define MBEDTLS_PLATFORM_SNPRINTF_MACRO snprintf
#endif

#ifndef MBEDTLS_AES_C
#define MBEDTLS_AES_C
#endif
#if (MBEDTLS_VERSION_NUMBER >= 0x03050000)
#ifndef MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH
#define MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH
#endif
#endif
#ifndef MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_AES_ROM_TABLES
#endif
#ifndef MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_PARSE_C
#endif
#ifndef MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_ASN1_WRITE_C
#endif
#ifndef MBEDTLS_BIGNUM_C
#define MBEDTLS_BIGNUM_C
#endif
#if (MBEDTLS_VERSION_NUMBER >= 0x03050000)
//#ifndef MBEDTLS_BLOCK_CIPHER_NO_DECRYPT
//#define MBEDTLS_BLOCK_CIPHER_NO_DECRYPT
//#endif
#endif
#ifndef MBEDTLS_CCM_C
#define MBEDTLS_CCM_C
#endif
#ifndef MBEDTLS_CIPHER_C
#define MBEDTLS_CIPHER_C
#endif
#ifndef MBEDTLS_CMAC_C
#define MBEDTLS_CMAC_C
#endif
#ifndef MBEDTLS_CTR_DRBG_C
#define MBEDTLS_CTR_DRBG_C
#endif
#ifndef MBEDTLS_DEPRECATED_REMOVED
#define MBEDTLS_DEPRECATED_REMOVED
#endif
#ifndef MBEDTLS_DEPRECATED_WARNING
#define MBEDTLS_DEPRECATED_WARNING
#endif
#ifndef MBEDTLS_ECJPAKE_C
#define MBEDTLS_ECJPAKE_C
#endif
#ifndef MBEDTLS_ECP_C
#define MBEDTLS_ECP_C
#endif
#ifndef MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#endif
#ifndef MBEDTLS_ECP_NIST_OPTIM
#define MBEDTLS_ECP_NIST_OPTIM
#endif
#ifndef MBEDTLS_ENTROPY_C
#define MBEDTLS_ENTROPY_C
#endif
#ifndef MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_ASM
#endif
#ifndef MBEDTLS_HMAC_DRBG_C
#define MBEDTLS_HMAC_DRBG_C
#endif
#ifndef MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
#endif
#ifndef MBEDTLS_MD_C
#define MBEDTLS_MD_C
#endif
#ifndef MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#endif
#ifndef MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_NO_PLATFORM_ENTROPY
#endif
#ifndef MBEDTLS_OID_C
#define MBEDTLS_OID_C
#endif
#ifndef MBEDTLS_PK_C
#define MBEDTLS_PK_C
#endif
#ifndef MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_PARSE_C
#endif
#ifndef MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_C
#endif
#ifndef MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_MEMORY
#endif
#ifndef MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#endif
#ifndef MBEDTLS_SHA224_C
#define MBEDTLS_SHA224_C
#endif
#ifndef MBEDTLS_SHA256_C
#define MBEDTLS_SHA256_C
#endif
#ifndef MBEDTLS_SHA256_SMALLER
#define MBEDTLS_SHA256_SMALLER
#endif
#ifndef MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_CLI_C
#endif
#ifndef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#define MBEDTLS_SSL_DTLS_ANTI_REPLAY
#endif
#ifndef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#define MBEDTLS_SSL_DTLS_HELLO_VERIFY
#endif
#ifndef MBEDTLS_SSL_EXPORT_KEYS
#define MBEDTLS_SSL_EXPORT_KEYS
#endif
#ifndef MBEDTLS_SSL_MAX_FRAGMENT_LENGTH
#define MBEDTLS_SSL_MAX_FRAGMENT_LENGTH
#endif
#ifndef MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_PROTO_TLS1_2
#endif
#ifndef MBEDTLS_SSL_PROTO_DTLS
#define MBEDTLS_SSL_PROTO_DTLS
#endif
#ifndef MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_TLS_C
#endif

#if OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE || OPENTHREAD_CONFIG_COMMISSIONER_ENABLE || OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE
#ifndef MBEDTLS_SSL_COOKIE_C
#define MBEDTLS_SSL_COOKIE_C
#endif
#ifndef MBEDTLS_SSL_SRV_C
#define MBEDTLS_SSL_SRV_C
#endif
#endif

#if OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE
#ifndef MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#define MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#endif
#endif

#if OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE || OPENTHREAD_CONFIG_TLS_ENABLE
#ifndef MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#endif
#endif

#if OPENTHREAD_CONFIG_BLE_TCAT_ENABLE
#ifndef MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#endif
#ifndef MBEDTLS_GCM_C
#define MBEDTLS_GCM_C
#endif
#endif

#ifdef MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#ifndef MBEDTLS_BASE64_C
#define MBEDTLS_BASE64_C
#endif
#ifndef MBEDTLS_ECDH_C
#define MBEDTLS_ECDH_C
#endif
#ifndef MBEDTLS_ECDSA_C
#define MBEDTLS_ECDSA_C
#endif
#ifndef MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PEM_PARSE_C
#endif
#ifndef MBEDTLS_X509_USE_C
#define MBEDTLS_X509_USE_C
#endif
#ifndef MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRT_PARSE_C
#endif
#endif

#if OPENTHREAD_CONFIG_ECDSA_ENABLE
#ifndef MBEDTLS_BASE64_C
#define MBEDTLS_BASE64_C
#endif
#ifndef MBEDTLS_ECDH_C
#define MBEDTLS_ECDH_C
#endif
#ifndef MBEDTLS_ECDSA_C
#define MBEDTLS_ECDSA_C
#endif
#if OPENTHREAD_CONFIG_DETERMINISTIC_ECDSA_ENABLE
#ifndef MBEDTLS_ECDSA_DETERMINISTIC
#define MBEDTLS_ECDSA_DETERMINISTIC
#endif
#endif
#ifndef MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PEM_PARSE_C
#endif
#ifndef MBEDTLS_PK_WRITE_C
#define MBEDTLS_PK_WRITE_C
#endif
#endif

#ifndef MBEDTLS_MPI_WINDOW_SIZE
#define MBEDTLS_MPI_WINDOW_SIZE            1 /**< Maximum windows size used. */
#endif
#ifndef MBEDTLS_MPI_MAX_SIZE
#define MBEDTLS_MPI_MAX_SIZE              32 /**< Maximum number of bytes for usable MPIs. */
#endif
//#ifndef MBEDTLS_ECP_MAX_BITS
//#define MBEDTLS_ECP_MAX_BITS             256 /**< Maximum bit size of groups */
//#endif
#ifndef MBEDTLS_ECP_WINDOW_SIZE
#define MBEDTLS_ECP_WINDOW_SIZE            2 /**< Maximum window size used */
#endif
#ifndef MBEDTLS_ECP_FIXED_POINT_OPTIM
#define MBEDTLS_ECP_FIXED_POINT_OPTIM      0 /**< Enable fixed-point speed-up */
#endif
#ifndef MBEDTLS_ENTROPY_MAX_SOURCES
#define MBEDTLS_ENTROPY_MAX_SOURCES        1 /**< Maximum number of sources supported */
#endif

#if OPENTHREAD_CONFIG_HEAP_EXTERNAL_ENABLE
//#ifndef MBEDTLS_PLATFORM_STD_CALLOC
//#define MBEDTLS_PLATFORM_STD_CALLOC      otPlatCAlloc /**< Default allocator to use, can be undefined */
//#endif
//#ifndef MBEDTLS_PLATFORM_STD_FREE
//#define MBEDTLS_PLATFORM_STD_FREE        otPlatFree /**< Default free to use, can be undefined */
//#endif
#else
#ifndef MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#endif
#endif

#ifndef MBEDTLS_SSL_MAX_CONTENT_LEN
#if OPENTHREAD_CONFIG_BLE_TCAT_ENABLE
#define MBEDTLS_SSL_MAX_CONTENT_LEN      2000 /**< Maxium fragment length in bytes */
#elif OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE
#define MBEDTLS_SSL_MAX_CONTENT_LEN      900 /**< Maxium fragment length in bytes */
#else
#define MBEDTLS_SSL_MAX_CONTENT_LEN      768 /**< Maxium fragment length in bytes */
#endif
#endif

#ifndef MBEDTLS_SSL_IN_CONTENT_LEN
#define MBEDTLS_SSL_IN_CONTENT_LEN       MBEDTLS_SSL_MAX_CONTENT_LEN
#endif
#ifndef MBEDTLS_SSL_OUT_CONTENT_LEN
#define MBEDTLS_SSL_OUT_CONTENT_LEN      MBEDTLS_SSL_MAX_CONTENT_LEN
#endif
#ifndef MBEDTLS_SSL_CIPHERSUITES
#define MBEDTLS_SSL_CIPHERSUITES         MBEDTLS_TLS_ECJPAKE_WITH_AES_128_CCM_8
#endif
#else //use openthread mbedtls config

#ifndef OPENTHREAD_CONFIG_CORE_USER_CONFIG_HEADER_ENABLE
#define OPENTHREAD_CONFIG_CORE_USER_CONFIG_HEADER_ENABLE
#endif

#include "mbedtls-config.h"

#ifndef MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT
#define MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT 0
#endif

#ifndef MBEDTLS_SSL_DTLS_CONNECTION_ID
#define MBEDTLS_SSL_DTLS_CONNECTION_ID
#endif

#ifndef MBEDTLS_NET_C
#define MBEDTLS_NET_C
#endif

#endif

#endif