# This file is generated automatically by : python menuconfig.py -s prj.conf
CONFIG_RMESH_EN=y
CONFIG_RMESH_SOCKET_EN=y
CONFIG_BT_MENU=y
CONFIG_BT_EXAMPLE_DEMO_MENU=y
CONFIG_BT_WIFIMATE_DEVICE=y
CONFIG_BT_WIFIMATE_CONFIGURATOR=y
