/*
 * Copyright (c) 2024 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * rdp_mutual_auth_ecdsa -- ECDSA P-256 mTLS client (board) connecting to local Python server
 *
 * Architecture:
 *   - Trust root : self-signed ECDSA P-256 CA (generated by gen_certs.sh)
 *   - Server cert: signed by the CA, SAN = server WiFi IP
 *   - Client cert: signed by the CA, client ECDSA private key d lives in image3 (S-World)
 *   - Cipher suite: TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256 (forced)
 *
 * Private key routing (CertificateVerify):
 *   mbedtls TLS state machine
 *     -> mbedtls_pk_sign_restartable
 *       -> pk_info->sign_func  (g_ecc_nsc_info, defined below)
 *         -> secure_ecc_client_sign NSC  (image3, S-heap ECDSA private key)
 *
 * NS side holds:
 *   - CA cert PEM (public trust anchor)
 *   - Client cert PEM (public; returned from S-side via secure_ecc_client_init)
 *   - proxy mbedtls_pk_context with custom pk_info -- no private key bytes here
 *
 * SETUP before building:
 *   1. Run example/peripheral/raw/RDP/rdp_mutual_auth_ecdsa/server/gen_certs.sh with SERVER_IP=<server WiFi IP>
 *   2. Paste ca_crt_pem.txt    -> ca_crt_pem[] below
 *   3. Paste client_d_array.txt  -> s_cli_d[] in secure_ecdsa_client_service.c
 *   4. Paste client_crt_pem.txt  -> s_cli_cert_pem[] in secure_ecdsa_client_service.c
 *   5. Set SERVER_HOST to the server WiFi IP (same IP used for the server cert SAN)
 */

#include "ameba_soc.h"
#include "os_wrapper.h"
#include "lwip_netconf.h"
#include "secure_ecdsa_client_service.h"
#include "wifi_api.h"

#include "mbedtls/ssl.h"
#include "mbedtls/net_sockets.h"
#include "mbedtls/x509_crt.h"
#include "mbedtls/pk.h"
#include "mbedtls/ssl_ciphersuites.h"

/*
 * pk_wrap.h declares struct mbedtls_pk_info_t -- internal mbedtls header.
 * Provides the type required to register the custom ECDSA sign callback.
 * The mbedtls-3.6.5/library directory is added to private_includes in CMakeLists.
 */
#include "pk_wrap.h"

#include <string.h>

static const char *const TAG = "ECDSA_MTLS";

/* -------------------------------------------------------------------------- */
/* Configuration -- update after running gen_certs.sh                         */
/* -------------------------------------------------------------------------- */
#define WIFI_SSID       "<your_wifi_ssid>"      /* replace with your AP SSID     */
#define WIFI_PASSWORD   "<your_wifi_password>"  /* replace with your AP password  */

/* SERVER_HOST: IP address of the PC running ecdsa_mtls_server.py (same LAN as board).
 * Must match the SERVER_IP used when running gen_certs.sh (embedded in server cert SAN). */
#define SERVER_HOST     "<server_ip>"    /* replace with the server PC's WiFi IP             */
#define SERVER_PORT     "8443"

#define HTTP_REQUEST    \
    "GET / HTTP/1.1\r\n"   \
    "Host: " SERVER_HOST "\r\n" \
    "Connection: close\r\n\r\n"

/* -------------------------------------------------------------------------- */
/* CA certificate PEM -- trust anchor for verifying the server certificate    */
/* Paste the content of ca_crt_pem.txt from gen_certs.sh here.                */
/* -------------------------------------------------------------------------- */
static const char ca_crt_pem[] =
	/* Generated by server/gen_certs.sh. Re-run gen_certs.sh and paste
	 * ca_crt_pem.txt here whenever the certificate suite is regenerated. */
	"-----BEGIN CERTIFICATE-----\r\n"
	"MIIBsjCCAVegAwIBAgIUEOATp/YoEO55+KS6HS+XXJ2YUL4wCgYIKoZIzj0EAwIw\r\n"
	"LjERMA8GA1UECgwIUlRLIERlbW8xGTAXBgNVBAMMEFJUSyBEZW1vIFJvb3QgQ0Ew\r\n"
	"HhcNMjYwNzI2MDM1MzE1WhcNMzYwNzIzMDM1MzE1WjAuMREwDwYDVQQKDAhSVEsg\r\n"
	"RGVtbzEZMBcGA1UEAwwQUlRLIERlbW8gUm9vdCBDQTBZMBMGByqGSM49AgEGCCqG\r\n"
	"SM49AwEHA0IABLrpLCNG2tzhmPLmfk04PBxLTnzMSU5t4IRcmFBKbCdmrtv5Qig4\r\n"
	"LvK9gWCRMY1rmz5DALLKjEPi33fRdGlmMLGjUzBRMB0GA1UdDgQWBBQX9mtSPX86\r\n"
	"OxPth3wZ0br9IqqmPTAfBgNVHSMEGDAWgBQX9mtSPX86OxPth3wZ0br9IqqmPTAP\r\n"
	"BgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0kAMEYCIQDlsRv6s5I3n9NraQOO\r\n"
	"/zq3AixPni8KGZYgtrLxqgHjkwIhAJOzE0V/JpjfXPImDxCmCQjlsgPb+1YgBfLW\r\n"
	"11DGBWyX\r\n"
	"-----END CERTIFICATE-----\r\n"
	;

/* -------------------------------------------------------------------------- */
/* Custom mbedtls_pk_info_t -- routes ECDSA signing to Secure World via NSC   */
/* -------------------------------------------------------------------------- */

/*
 * get_bitlen: tell mbedtls this is a 256-bit key (P-256).
 * Required for cipher suite matching (ECDHE-ECDSA needs >= 256-bit key).
 */
static size_t ecc_nsc_get_bitlen(mbedtls_pk_context *pk)
{
	(void)pk;
	return 256;
}

/*
 * can_do: report that this pk_context can perform ECKEY and ECDSA operations.
 * Called by mbedtls TLS to verify the key type matches the cipher suite.
 */
static int ecc_nsc_can_do(mbedtls_pk_type_t type)
{
	return (type == MBEDTLS_PK_ECKEY || type == MBEDTLS_PK_ECDSA);
}

/*
 * sign_func: called by mbedtls_pk_sign_restartable during CertificateVerify.
 *
 *   hash/hash_len: pre-computed transcript hash (SHA-256, 32 bytes for P-256)
 *   sig/sig_size : output buffer for DER signature
 *   sig_len      : actual DER bytes written
 *
 * Routes to secure_ecc_client_sign NSC -> S-heap ECDSA private key d.
 * The private key NEVER crosses the S/NS boundary.
 */
static int ecc_nsc_sign(mbedtls_pk_context *pk,
						mbedtls_md_type_t   md_alg,
						const unsigned char *hash, size_t hash_len,
						unsigned char *sig, size_t sig_size, size_t *sig_len,
						int (*f_rng)(void *, unsigned char *, size_t), void *p_rng)
{
	(void)pk;
	(void)f_rng;
	(void)p_rng;  /* S-side uses TRNG_get_random_bytes_f_rng directly */

	secure_ecc_sign_req_t req;
	req.md_alg   = (unsigned int)md_alg;
	req.hash     = hash;
	req.hash_len = (unsigned int)hash_len;
	req.sig      = sig;
	req.sig_size = sig_size;  /* passed to S-side for bounds check */
	req.sig_len  = sig_len;

	return secure_ecc_client_sign(&req);  /* NSC call -> S-side sign */
}

/*
 * g_ecc_nsc_info: custom pk_info registered via mbedtls_pk_setup().
 *
 * Only sign_func, get_bitlen, and can_do are needed for mTLS client auth.
 * All other callbacks (verify, encrypt, decrypt, check_pair, debug) are NULL.
 *
 * Note: MBEDTLS_ECP_RESTARTABLE is disabled in this SDK build (RTL8720F,
 *       mbedtls-3.6.5), so sign_rs_func does not exist in the struct and
 *       mbedtls_pk_sign_restartable falls through directly to sign_func.
 */
static const mbedtls_pk_info_t g_ecc_nsc_info = {
	.type            = MBEDTLS_PK_ECKEY,
	.name            = "ECKEY-NSC",
	.get_bitlen      = ecc_nsc_get_bitlen,
	.can_do          = ecc_nsc_can_do,
	.verify_func     = NULL,
	.sign_func       = ecc_nsc_sign,
	.decrypt_func    = NULL,
	.encrypt_func    = NULL,
	.check_pair_func = NULL,
	.ctx_alloc_func  = NULL,  /* no heap allocation: pk_ctx stays NULL */
	.ctx_free_func   = NULL,
	.debug_func      = NULL,
};

/* -------------------------------------------------------------------------- */
/* Certificate verify callback                                                 */
/* -------------------------------------------------------------------------- */
static int cert_verify_cb(void *data, mbedtls_x509_crt *crt,
						  int depth, uint32_t *flags)
{
	(void)data;
	(void)crt;
	if (*flags == 0) {
		RTK_LOGI(TAG, "  cert OK (depth %d)\n", depth);
	} else {
		RTK_LOGI(TAG, "  cert FAIL depth=%d flags=0x%08x\n",
				 depth, (unsigned)*flags);
	}
	return 0;
}

/* -------------------------------------------------------------------------- */
/* Demo task                                                                   */
/* -------------------------------------------------------------------------- */
static void demo_task(void *param)
{
	(void)param;
	int ret;

	RTK_LOGI(TAG, "=== ECDSA mTLS Client Demo ===\n");
	RTK_LOGI(TAG, "Client key in Secure World (image3), sign via NSC\n");
	RTK_LOGI(TAG, "Cipher: ECDHE-ECDSA-AES128-GCM-SHA256\n");

	/* Step 1: Allocate secure context for this task on S-heap */
	rtos_create_secure_context(2048);

	/* Step 2: Load client private key into S-side; receive cert PEM back */
	static char cert_buf[SEC_ECC_CERT_MAX_LEN];
	size_t cert_len = 0;
	secure_ecc_init_req_t init_req;
	init_req.cert_pem = (unsigned char *)cert_buf;
	init_req.cert_max = sizeof(cert_buf);
	init_req.cert_len = &cert_len;

	ret = secure_ecc_client_init(&init_req);
	if (ret != 0) {
		RTK_LOGI(TAG, "secure_ecc_client_init failed %d\n", ret);
		goto out;
	}
	RTK_LOGI(TAG, "S-side ECDSA key ready, cert_len=%u B\n", (unsigned)cert_len);

	/* Step 3: Connect to WiFi and obtain IP address */
	RTK_LOGI(TAG, "Connecting to WiFi \"%s\" ...\n", WIFI_SSID);
	{
		struct rtw_network_info wparam = {0};
		_memcpy(wparam.ssid.val, WIFI_SSID, strlen(WIFI_SSID));
		wparam.ssid.len     = strlen(WIFI_SSID);
		wparam.password     = (unsigned char *)WIFI_PASSWORD;
		wparam.password_len = strlen(WIFI_PASSWORD);

		int wret = wifi_connect(&wparam, 1);
		if (wret == RTK_SUCCESS) {
			if (lwip_request_ip(NETIF_WLAN_STA_INDEX) != DHCP_ADDRESS_ASSIGNED) {
				RTK_LOGI(TAG, "DHCP failed\n");
				goto out;
			}
		} else {
			int wait = 0;
			while (lwip_check_connectivity(NETIF_WLAN_STA_INDEX) != CONNECTION_VALID
				   && wait++ < 30) {
				rtos_time_delay_ms(1000);
			}
			if (lwip_check_connectivity(NETIF_WLAN_STA_INDEX) != CONNECTION_VALID) {
				RTK_LOGI(TAG, "No IP, abort\n");
				goto out;
			}
		}
	}
	{
		unsigned char *ip = lwip_get_ip(NETIF_WLAN_STA_INDEX);
		RTK_LOGI(TAG, "WiFi ready, IP: %d.%d.%d.%d\n",
				 ip[0], ip[1], ip[2], ip[3]);
	}

	/* Step 4: Set up mbedtls TLS client */
	mbedtls_net_context  server_fd;
	mbedtls_ssl_context  ssl;
	mbedtls_ssl_config   conf;
	mbedtls_x509_crt     ca_crt;
	mbedtls_x509_crt     cli_crt;   /* NS holds certificate only, no private key */
	mbedtls_pk_context   proxy_pk;  /* proxy: sign routed to S-side NSC */

	mbedtls_net_init(&server_fd);
	mbedtls_ssl_init(&ssl);
	mbedtls_ssl_config_init(&conf);
	mbedtls_x509_crt_init(&ca_crt);
	mbedtls_x509_crt_init(&cli_crt);
	mbedtls_pk_init(&proxy_pk);

	/* Load CA certificate (trust anchor for verifying the server) */
	ret = mbedtls_x509_crt_parse(&ca_crt,
								 (const unsigned char *)ca_crt_pem,
								 strlen(ca_crt_pem) + 1);
	if (ret != 0) {
		RTK_LOGI(TAG, "ca_crt parse fail %d\n", ret);
		goto tls_cleanup;
	}

	/* Load client certificate (PEM received from S-side, no private key here) */
	ret = mbedtls_x509_crt_parse(&cli_crt,
								 (const unsigned char *)cert_buf,
								 cert_len);
	if (ret != 0) {
		RTK_LOGI(TAG, "cli_crt parse fail %d\n", ret);
		goto tls_cleanup;
	}

	/*
	 * Set up proxy pk_context with custom pk_info:
	 *   - get_bitlen returns 256 (P-256)
	 *   - can_do returns true for MBEDTLS_PK_ECKEY / MBEDTLS_PK_ECDSA
	 *   - sign_func routes to secure_ecc_client_sign NSC -> S-heap key
	 *   - pk_ctx stays NULL (ctx_alloc_func is NULL)
	 *
	 * mbedtls_pk_init already set pk_info = NULL, so mbedtls_pk_setup
	 * will succeed.
	 */
	ret = mbedtls_pk_setup(&proxy_pk, &g_ecc_nsc_info);
	if (ret != 0) {
		RTK_LOGI(TAG, "pk_setup fail %d\n", ret);
		goto tls_cleanup;
	}

	/* TLS configuration */
	ret = mbedtls_ssl_config_defaults(&conf,
									  MBEDTLS_SSL_IS_CLIENT,
									  MBEDTLS_SSL_TRANSPORT_STREAM,
									  MBEDTLS_SSL_PRESET_DEFAULT);
	if (ret != 0) {
		RTK_LOGI(TAG, "config_defaults fail %d\n", ret);
		goto tls_cleanup;
	}

	/* Force cipher suite: ECDHE-ECDSA-AES128-GCM-SHA256 */
	static const int forced_ciphersuites[] = {
		MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
		0
	};
	mbedtls_ssl_conf_ciphersuites(&conf, forced_ciphersuites);

	mbedtls_ssl_conf_rng(&conf, TRNG_get_random_bytes_f_rng, NULL);
	mbedtls_ssl_conf_verify(&conf, cert_verify_cb, NULL);

	/* Server authentication: verify server cert against our CA */
	mbedtls_ssl_conf_ca_chain(&conf, &ca_crt, NULL);
	mbedtls_ssl_conf_authmode(&conf, MBEDTLS_SSL_VERIFY_REQUIRED);

	/* Client authentication: send client cert + route signing to S-side */
	ret = mbedtls_ssl_conf_own_cert(&conf, &cli_crt, &proxy_pk);
	if (ret != 0) {
		RTK_LOGI(TAG, "conf_own_cert fail %d\n", ret);
		goto tls_cleanup;
	}

	ret = mbedtls_ssl_setup(&ssl, &conf);
	if (ret != 0) {
		RTK_LOGI(TAG, "ssl_setup fail %d\n", ret);
		goto tls_cleanup;
	}

	ret = mbedtls_ssl_set_hostname(&ssl, SERVER_HOST);
	if (ret != 0) {
		RTK_LOGI(TAG, "set_hostname fail %d\n", ret);
		goto tls_cleanup;
	}

	/* TCP connect */
	RTK_LOGI(TAG, "Connecting to %s:%s ...\n", SERVER_HOST, SERVER_PORT);
	ret = mbedtls_net_connect(&server_fd, SERVER_HOST, SERVER_PORT,
							  MBEDTLS_NET_PROTO_TCP);
	if (ret != 0) {
		RTK_LOGI(TAG, "net_connect fail %d\n", ret);
		goto tls_cleanup;
	}

	mbedtls_ssl_set_bio(&ssl, &server_fd,
						mbedtls_net_send, mbedtls_net_recv, NULL);

	/* TLS handshake:
	 *   During ClientCertificateVerify mbedtls calls sign_func in g_ecc_nsc_info,
	 *   which routes to secure_ecc_client_sign NSC -> S-heap ECDSA key.
	 *   Mutual auth: board verifies server cert (ca_crt), server verifies client cert. */
	RTK_LOGI(TAG, "TLS handshake ...\n");
	ret = mbedtls_ssl_handshake(&ssl);
	if (ret != 0) {
		RTK_LOGI(TAG, "Handshake FAIL %d\n", ret);
		goto tls_cleanup;
	}
	RTK_LOGI(TAG, "Handshake OK\n");
	RTK_LOGI(TAG, "Cipher: %s\n", mbedtls_ssl_get_ciphersuite(&ssl));

	/* HTTP GET / */
	RTK_LOGI(TAG, "Sending HTTP GET / ...\n");
	ret = mbedtls_ssl_write(&ssl,
							(const unsigned char *)HTTP_REQUEST,
							strlen(HTTP_REQUEST));
	if (ret < 0) {
		RTK_LOGI(TAG, "ssl_write fail %d\n", ret);
		goto tls_cleanup;
	}

	/* Read and print server response */
	{
		unsigned char buf[512];
		int total = 0;
		int first = 1;
		do {
			memset(buf, 0, sizeof(buf));
			ret = mbedtls_ssl_read(&ssl, buf, sizeof(buf) - 1);
			if (ret <= 0) {
				break;
			}
			if (first) {
				buf[ret] = 0;
				char *end = (char *)buf;
				while (*end && *end != '\r' && *end != '\n') {
					end++;
				}
				*end = 0;
				RTK_LOGI(TAG, "%s\n", (char *)buf);
				first = 0;
			}
			total += ret;
		} while (ret > 0);
		RTK_LOGI(TAG, "Total bytes received: %d\n", total);
	}

	mbedtls_ssl_close_notify(&ssl);
	RTK_LOGI(TAG, "=== Demo Complete: ECDSA mTLS PASS, GCM PASS ===\n");
	RTK_LOGI(TAG, "NS heap free now : %u B\n",
			 (unsigned)rtos_mem_get_free_heap_size());
	RTK_LOGI(TAG, "NS heap min ever : %u B\n",
			 (unsigned)rtos_mem_get_minimum_ever_free_heap_size());

tls_cleanup:
	mbedtls_ssl_free(&ssl);
	mbedtls_ssl_config_free(&conf);
	mbedtls_net_free(&server_fd);
	mbedtls_x509_crt_free(&ca_crt);
	mbedtls_x509_crt_free(&cli_crt);
	mbedtls_pk_free(&proxy_pk);
out:
	rtos_task_delete(NULL);
}

/* -------------------------------------------------------------------------- */
/* Entry point                                                                 */
/* -------------------------------------------------------------------------- */
void example_rdp_mutual_auth_ecdsa(void)
{
#ifdef CONFIG_TRUSTZONE
	if (rtos_task_create(NULL, "ecdsa_mtls", (rtos_task_t)demo_task,
						 NULL, 1024 * 12, 1) != RTK_SUCCESS) {
		RTK_LOGI(TAG, "create demo_task failed\n");
	}
#else
	RTK_LOGE(TAG, "Please enable TrustZone in menuconfig\n");
#endif
}
