# This file is generated automatically by : python menuconfig.py -s tools/scripts/daily_build_tool/amebalite/confs_daily_build/kr4_singlecore.conf
CONFIG_WIFI_SINGLE_CORE_MENU=y
CONFIG_WHC_HOST_LOC_KR4_MENU=y
