set(
    WIFI_IFLAGS
    ${BASEDIR}/component/wifi/wifi_reg/common
    ${BASEDIR}/component/wifi/wpa_supplicant/src
    ${BASEDIR}/component/wifi/wpa_supplicant/src/crypto
    ${BASEDIR}/component/wifi/wpa_supplicant/wpa_supplicant
    ${BASEDIR}/component/wifi/wifi_fast_connect
    ${BASEDIR}/component/wifi/wifi_auto_reconnect
    ${BASEDIR}/component/wifi/simple_config
    ${BASEDIR}/component/wifi/common
    ${BASEDIR}/component/wifi/wpa_supplicant/wpa_lite
    ${BASEDIR}/component/wifi/wpa_supplicant/wpa_lite/rom
    ${BASEDIR}/component/at_cmd
)
