# This file is generated automatically by : python menuconfig.py -s utils/confs_daily_build/audio_mixer_ca32_ap_km4_np.conf
CONFIG_AUDIO_FWK_MENU=y
CONFIG_MEDIA_PLAYER_MENU=y
CONFIG_MEDIA_FORMAT_WAV_MENU=y
CONFIG_MEDIA_FORMAT_MP3_MENU=y
CONFIG_MEDIA_FORMAT_AAC_MENU=y
CONFIG_MEDIA_FORMAT_M4A_MENU=y
CONFIG_MEDIA_FORMAT_FLAC_MENU=y
CONFIG_MEDIA_FORMAT_AMR_MENU=y
CONFIG_MEDIA_FORMAT_OGG_MENU=y
CONFIG_MEDIA_OGG_VORBIS_MENU=y
CONFIG_MEDIA_OGG_OPUS_MENU=y
CONFIG_THIRD_PARTY_SPEEXDSP_MENU=y
CONFIG_THIRD_PARTY_OPUS_MENU=y
