# Kbuild for WHC firmware download module (COMMON LIBRARY)

ifeq ($(CONFIG_FW_DOWNLOAD), y)
# Include paths
ccflags-y += -I$(src)/.. -I$(src)/../include

# Common XFER files
FWDL_OBJS := \
	whc_host_xfer.o \
	whc_host_xfer_dl.o

# SDIO interface specific files
FWDL_OBJS-$(CONFIG_WHC_HCI_SDIO) += \
	whc_sdio_host_rom.o \
	whc_sdio_host_xfer.o \
	whc_sdio_host_fwdl.o

# USB interface specific files
FWDL_OBJS-$(CONFIG_WHC_HCI_USB) += \
	whc_usb_host_xfer.o \
	whc_usb_host_fwdl.o

ifeq ($(CONFIG_AMEBAGREEN2), y)
FWDL_OBJS += whc_hal_rtl8721f.o
else
$(error No valid IC selected for fwdl HAL.)
endif

FWDL_OBJS += $(FWDL_OBJS-y)
endif
