ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_IEEE80211R) += -DCONFIG_IEEE80211R
ccflags-$(CONFIG_BT_INIC) += -DCONFIG_BT_INIC
ccflags-$(CONFIG_WHC_HCI_SPI) += -DCONFIG_WHC_HCI_SPI
ccflags-$(CONFIG_WHC_CMD_PATH) += -DCONFIG_WHC_CMD_PATH
ccflags-$(CONFIG_WHC_WIFI_API_PATH) += -DCONFIG_WHC_WIFI_API_PATH
ccflags-$(CONFIG_SUPPLICANT_SME) += -DCONFIG_SUPPLICANT_SME

ccflags-y += -DCONFIG_FULLMAC
ccflags-y += -I$(src)/../netdev
ccflags-y += -I$(src)/../include -I$(src)/.. -I$(src)/../../common -I$(src)/../spi

whc_spi-$(CONFIG_WHC_HCI_SPI) := \
		../spi/whc_spi_host_ops.o \
		../spi/whc_spi_host_probe.o \
		../netdev/whc_host_drv_probe.o \
		../netdev/whc_host_ethtool_ops.o \
		../netdev/whc_host_netdev_ops.o \
		../whc_host_pkt_tx.o \
		../whc_host_pkt_rx.o \
		../whc_host_memory.o \
		../whc_host_hci.o \
		../whc_host_ops.o \
		../whc_host_wiphy.o \
		../whc_host_regd.o \
		../whc_host_ft.o \
		../whc_host_ops_ap.o \
		../whc_host_ops_key.o \
		../whc_host_ops_nan.o \
		../whc_host_ops_p2p.o \
		../whc_host_netdev_ops_p2p.o \
		../whc_host_cfgvendor.o \
		../whc_host_proc.o \
		../whc_host_event_tx.o \
		../whc_host_event_rx.o \
		../whc_host_protocal_offload.o \
		../whc_host_ioctl.o \
		../whc_host_cust_evt.o \
		../whc_host_acs.o

whc_spi-$(CONFIG_BT_INIC) += rtb_spi.o

ifeq ($(CONFIG_WHC_CMD_PATH), y)
    whc_spi-$(CONFIG_WHC_HCI_SPI) += \
            ../whc_host_netlink.o \
            ../whc_host_cmd_path_tx.o
endif

obj-m += whc_spi.o
