ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_WHC_BRIDGE) += -DCONFIG_WHC_BRIDGE

ccflags-y += -DCONFIG_FULLMAC -DCONFIG_FULLMAC_HCI_SDIO
ccflags-y += -I$(src)/../../common/netdev
ccflags-y += -I$(src)/../../bridge
ccflags-y += -I$(src)/../../common/include -I$(src)/.. -I$(src)/../../common -I$(src)/../../common/sdio -I$(src)

bridge_sdio-y := \
		../../common/sdio/whc_sdio_host_drvio.o \
		../../common/sdio/whc_sdio_host_ops.o \
		../../common/sdio/whc_sdio_host_probe.o \
		../../common/sdio/whc_sdio_host_init.o	\
		../../common/netdev/whc_host_drv_probe.o \
		../../common/netdev/whc_host_ethtool_ops.o \
		../../common/netdev/whc_host_netdev_ops.o \
		../../common/whc_host_ops.o \
		../../common/whc_host_pkt_tx.o \
		../../common/whc_host_pkt_rx.o \
		../../common/whc_host_memory.o \
		../../common/whc_host_hci.o \
		../whc_bridge_host_tx.o \
		../whc_bridge_host_pkt_rx.o \
		../whc_bridge_host_netlink.o \
		../sdio_bridge/whc_bridge_host_sdio.o

ifeq ($(CONFIG_WHC_BRIDGE_WPA_OPS),y)

ccflags-y += -I$(src)/../../bridge/bridge_wpa_ops_demo

bridge_sdio-y += \
		../bridge_wpa_ops_demo/whc_bridge_wpa_ops_custom_netlink.o \
		../bridge_wpa_ops_demo/whc_bridge_wpa_ops_api.o \

endif

obj-m += bridge_sdio.o
