/*
 * Copyright (c) 2024 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * secure_ecdsa_client_service.c -- ECDSA P-256 client key service (Secure World)
 *
 * Security property:
 *   The client ECDSA P-256 private key scalar d (32 bytes) is stored as a raw
 *   byte array in this file (image3, Secure World only). On first call the scalar
 *   is imported directly into an mbedtls_ecdsa_context via mbedtls_mpi_read_binary(),
 *   bypassing mbedtls_pk_parse_key() entirely.
 *
 *   Signing is the only operation that needs d and grp. The public point Q is
 *   not computed here because mbedtls_ecdsa_sign() only accesses d and grp.
 *
 * NS side receives only:
 *   - Certificate PEM (public, safe to share)
 *   - ECDSA DER signatures produced by secure_ecc_client_sign()
 *
 * SETUP: Run server/gen_certs.sh to generate the certificate suite, then
 *        paste the output into the two arrays below:
 *           s_cli_d[]       <- client_d_array.txt  (private key scalar d)
 *           s_cli_cert_pem  <- client_crt_pem.txt  (client certificate PEM)
 */

#include "ameba_soc.h"
#include "secure_ecdsa_client_service.h"

#include "mbedtls/ecdsa.h"    /* mbedtls_ecdsa_context, write_signature; pulls in ecp.h + bignum.h */

#include <string.h>

#ifdef CONFIG_TRUSTZONE_MBEDTLS

extern size_t xPortGetFreeHeapSize(void);
extern size_t xPortGetMinimumEverFreeHeapSize(void);

static const char *const TAG = "SEC_ECC";

/* ── Client certificate PEM (public, safe to return to NS) ──────────────── */
/*
 * Generated by server/gen_certs.sh (client_crt_pem.txt).
 * Re-run gen_certs.sh and paste client_crt_pem.txt here whenever the
 * certificate suite is regenerated.
 */
static const char s_cli_cert_pem[] =
	"-----BEGIN CERTIFICATE-----\r\n"
	"MIIBtTCCAVugAwIBAgIUBHlO9Tx4aGu89KkguwFRM7KHy90wCgYIKoZIzj0EAwIw\r\n"
	"LjERMA8GA1UECgwIUlRLIERlbW8xGTAXBgNVBAMMEFJUSyBEZW1vIFJvb3QgQ0Ew\r\n"
	"HhcNMjYwNzI2MDM1MzE1WhcNMjgxMDI4MDM1MzE1WjAuMREwDwYDVQQKDAhSVEsg\r\n"
	"RGVtbzEZMBcGA1UEAwwQUlRLIEJvYXJkIENsaWVudDBZMBMGByqGSM49AgEGCCqG\r\n"
	"SM49AwEHA0IABI1Y9PWBd7nM/ov71LIEor673Y/0fPFxiTXq0r2ticjLU+hCWr92\r\n"
	"MdzmnoILCb9RPlO3e5U2k6u5rasGH0XQtI2jVzBVMBMGA1UdJQQMMAoGCCsGAQUF\r\n"
	"BwMCMB0GA1UdDgQWBBShfSHRuWSX+CSR04U7TlUNY/YYIzAfBgNVHSMEGDAWgBQX\r\n"
	"9mtSPX86OxPth3wZ0br9IqqmPTAKBggqhkjOPQQDAgNIADBFAiAu7Vg3UATM0sqy\r\n"
	"QFqppoVWNIkdGXQTDdFtL45Kn5VEuQIhAMJa3F7CX/xyXGwcw9tJ1iRsUTRrOt4b\r\n"
	"+69wUOZWYy/r\r\n"
	"-----END CERTIFICATE-----\r\n"
	;

/* ── ECDSA P-256 private key scalar d (32 bytes, big-endian) ─────────────── */
/*
 * Generated by server/gen_certs.sh (client_d_array.txt).
 * Re-run gen_certs.sh and paste the array body here whenever the
 * certificate suite is regenerated.
 *
 * SECURITY: This value NEVER leaves Secure World (image3 address space only).
 */
static const unsigned char s_cli_d[32] = {
	0x72, 0xe3, 0x94, 0x41, 0x80, 0x70, 0x3a, 0xa2,
	0x63, 0x5a, 0x14, 0xab, 0x22, 0xdf, 0x14, 0x82,
	0xb4, 0x11, 0x66, 0x5c, 0xbd, 0x39, 0x39, 0x62,
	0xdc, 0xda, 0xa9, 0x0c, 0x26, 0x2b, 0x3c, 0xba
};

/* ── Persistent ECDSA context in S-heap ─────────────────────────────────── */
static mbedtls_ecdsa_context g_ecc;
static int                   g_initialized = 0;

/* ── NSC: import key and return client cert PEM ──────────────────────────── */
IMAGE3_ENTRY_SECTION
NS_ENTRY int secure_ecc_client_init(const secure_ecc_init_req_t *req)
{
	int ret;

	if (req == NULL || req->cert_pem == NULL || req->cert_len == NULL) {
		RTK_LOGE(TAG, "init: invalid params\n");
		return -1;
	}

	if (!g_initialized) {
		mbedtls_ecdsa_init(&g_ecc);

		/*
		 * Load curve group: SECP256R1 (P-256).
		 * g_ecc is mbedtls_ecp_keypair; after this call g_ecc.grp is ready.
		 */
		ret = mbedtls_ecp_group_load(&g_ecc.grp, MBEDTLS_ECP_DP_SECP256R1);
		if (ret != 0) {
			RTK_LOGE(TAG, "ecp_group_load failed %d\n", ret);
			mbedtls_ecdsa_free(&g_ecc);
			return ret;
		}

		/*
		 * Import private key scalar d from raw big-endian bytes.
		 * Signing only needs grp and d; Q (public point) is not computed
		 * here to save S-heap and avoid the ecp_mul overhead.
		 */
		ret = mbedtls_mpi_read_binary(&g_ecc.d, s_cli_d, sizeof(s_cli_d));
		if (ret != 0) {
			RTK_LOGE(TAG, "mpi_read_binary(d) failed %d\n", ret);
			mbedtls_ecdsa_free(&g_ecc);
			return ret;
		}

		RTK_LOGI(TAG, "ECDSA P-256 client key loaded into Secure World\n");
		g_initialized = 1;
	}

	/* Copy certificate PEM to NS buffer (public info, safe to share) */
	size_t cert_len = strlen(s_cli_cert_pem) + 1;
	if (req->cert_max < cert_len) {
		RTK_LOGE(TAG, "cert buffer too small (%u < %u)\n",
				 (unsigned)req->cert_max, (unsigned)cert_len);
		return -1;
	}
	_memcpy(req->cert_pem, s_cli_cert_pem, cert_len);
	*req->cert_len = cert_len;
	return 0;
}

/* ── NSC: ECDSA P-256 sign with S-heap private key ──────────────────────── */
IMAGE3_ENTRY_SECTION
NS_ENTRY int secure_ecc_client_sign(const secure_ecc_sign_req_t *req)
{
	int ret;

	if (req == NULL || req->hash == NULL || req->sig == NULL || req->sig_len == NULL) {
		RTK_LOGE(TAG, "sign: invalid params\n");
		return -1;
	}
	if (!g_initialized) {
		RTK_LOGE(TAG, "sign: not initialized\n");
		return -1;
	}
	if (req->sig_size < SEC_ECC_SIG_MAX_LEN) {
		RTK_LOGE(TAG, "sign: sig buffer too small (%u < %u)\n",
				 (unsigned)req->sig_size, (unsigned)SEC_ECC_SIG_MAX_LEN);
		return -1;
	}

	RTK_LOGI(TAG, "S-side ECDSA sign: md_alg=%u hash_len=%u\n",
			 req->md_alg, req->hash_len);

	/*
	 * TRNG_get_random_bytes_f_rng has the exact mbedtls f_rng_t signature and
	 * propagates TRNG hardware errors. For non-deterministic ECDSA the nonce k
	 * comes entirely from this RNG; a failed/weak RNG would expose the private
	 * scalar d, so we must not swallow errors here.
	 *
	 * Output is DER-encoded (r, s): up to SEC_ECC_SIG_MAX_LEN bytes.
	 */
	ret = mbedtls_ecdsa_write_signature(&g_ecc,
										(mbedtls_md_type_t)req->md_alg,
										req->hash, req->hash_len,
										req->sig, req->sig_size, req->sig_len,
										TRNG_get_random_bytes_f_rng, NULL);
	if (ret != 0) {
		RTK_LOGE(TAG, "ecdsa_write_signature failed %d\n", ret);
		return ret;
	}

	RTK_LOGI(TAG, "S-side ECDSA sign OK, sig_len=%u B\n", (unsigned)*req->sig_len);

	/* S-heap watermark */
	size_t total = (size_t)__image3_heap_size__;
	size_t min   = xPortGetMinimumEverFreeHeapSize();
	size_t now   = xPortGetFreeHeapSize();
	RTK_LOGI(TAG, "S heap total:    %u B\n", (unsigned)total);
	RTK_LOGI(TAG, "S heap free now: %u B\n", (unsigned)now);
	RTK_LOGI(TAG, "S heap min ever: %u B\n", (unsigned)min);
	RTK_LOGI(TAG, "S heap peak used:%u B\n", (unsigned)(total - min));

	return 0;
}

#endif /* CONFIG_TRUSTZONE_MBEDTLS */
