list(
	APPEND CSRC 
	${ZB_STACK_DIR}/zcl/zcl_main.c
	${ZB_STACK_DIR}/zcl/zcl_general_commands.c
	${ZB_STACK_DIR}/zcl/zcl_attr_value.c
	${ZB_STACK_DIR}/zcl/zcl_common.c
	${ZB_STACK_DIR}/zcl/zcl_nvram.c
	${ZB_STACK_DIR}/zcl/zcl_reporting.c
	${ZB_STACK_DIR}/zcl/zcl_identify_commands.c
	${ZB_STACK_DIR}/zcl/zcl_on_off_commands.c
	${ZB_STACK_DIR}/zcl/ha_sas.c
	${ZB_STACK_DIR}/zcl/zcl_groups.c
	${ZB_STACK_DIR}/zcl/zcl_scenes.c
	${ZB_STACK_DIR}/zcl/zcl_level_control_commands.c
	${ZB_STACK_DIR}/zcl/zcl_shade_config_commands.c
	${ZB_STACK_DIR}/zcl/zcl_continuous_value_change_commands.c
	${ZB_STACK_DIR}/zcl/zcl_color_control_commands.c
	${ZB_STACK_DIR}/zcl/zcl_poll_control_commands.c
	${ZB_STACK_DIR}/zcl/zcl_poll_control_client.c
	${ZB_STACK_DIR}/zcl/zcl_alarms_commands.c
	${ZB_STACK_DIR}/zcl/zcl_power_config_commands.c
	${ZB_STACK_DIR}/zcl/zcl_diagnostics_commands.c
	${ZB_STACK_DIR}/zcl/zcl_ias_ace_commands.c
	${ZB_STACK_DIR}/zcl/zcl_ias_wd_commands.c
	${ZB_STACK_DIR}/zcl/zcl_ias_zone_commands.c
	${ZB_STACK_DIR}/zcl/zcl_ota_upgrade_commands.c
	${ZB_STACK_DIR}/zcl/zcl_ota_upgrade_srv_commands.c
	${ZB_STACK_DIR}/zcl/zcl_ota_upgrade_common.c
	${ZB_STACK_DIR}/zcl/zcl_ota_upgrade_minimal.c
	${ZB_STACK_DIR}/zcl/zcl_basic_commands.c
	${ZB_STACK_DIR}/zcl/zcl_temp_measurement.c
	${ZB_STACK_DIR}/zcl/zcl_pressure_measurement.c
	${ZB_STACK_DIR}/zcl/zcl_thermostat_commands.c
	${ZB_STACK_DIR}/zcl/zcl_tunnel.c 
	${ZB_STACK_DIR}/zcl/zcl_time.c
	${ZB_STACK_DIR}/zcl/zcl_en50523_appliance_events_and_alerts.c
	${ZB_STACK_DIR}/zcl/zcl_c_tunneling.c
	${ZB_STACK_DIR}/zcl/zcl_s_tunneling.c
	${ZB_STACK_DIR}/zcl/zcl_dehumid_control.c
	${ZB_STACK_DIR}/zcl/zcl_door_lock.c
	${ZB_STACK_DIR}/zcl/zcl_el_measurement.c
	${ZB_STACK_DIR}/zcl/zcl_fan_control.c
	${ZB_STACK_DIR}/zcl/zcl_rel_humidity.c
	${ZB_STACK_DIR}/zcl/zcl_thermostat_ui_config.c
	${ZB_STACK_DIR}/zcl/zcl_window_covering.c
	${ZB_STACK_DIR}/zcl/zcl_on_off_switch_config.c
	${ZB_STACK_DIR}/zcl/zcl_illuminance_measurement.c
	${ZB_STACK_DIR}/zcl/zcl_c_drlc.c
	${ZB_STACK_DIR}/zcl/zcl_s_drlc.c
	${ZB_STACK_DIR}/zcl/zcl_c_price.c
	${ZB_STACK_DIR}/zcl/zcl_s_price.c
	${ZB_STACK_DIR}/zcl/zcl_prepayment.c
	${ZB_STACK_DIR}/zcl/zcl_c_calendar.c
	${ZB_STACK_DIR}/zcl/zcl_s_calendar.c
	${ZB_STACK_DIR}/zcl/zcl_c_energy_mgmt.c
	${ZB_STACK_DIR}/zcl/zcl_s_energy_mgmt.c
	${ZB_STACK_DIR}/zcl/zcl_c_messaging.c
	${ZB_STACK_DIR}/zcl/zcl_s_messaging.c
	${ZB_STACK_DIR}/zcl/zcl_c_events.c
	${ZB_STACK_DIR}/zcl/zcl_s_events.c
	${ZB_STACK_DIR}/zcl/zcl_c_subghz.c
	${ZB_STACK_DIR}/zcl/zcl_s_subghz.c
	${ZB_STACK_DIR}/zcl/zcl_c_mdu_pairing.c
	${ZB_STACK_DIR}/zcl/zcl_s_mdu_pairing.c
	${ZB_STACK_DIR}/zcl/zcl_meter_identification.c
	${ZB_STACK_DIR}/zcl/zcl_s_metering.c
	${ZB_STACK_DIR}/zcl/zcl_c_metering.c
	${ZB_STACK_DIR}/zcl/zcl_device_management.c
	${ZB_STACK_DIR}/zcl/zcl_binary_input.c
	${ZB_STACK_DIR}/zcl/zcl_ir_blaster.c
	${ZB_STACK_DIR}/zcl/zcl_c_wwah.c
	${ZB_STACK_DIR}/zcl/zcl_s_wwah.c
	${ZB_STACK_DIR}/zcl/zcl_wwah_common.c
	${ZB_STACK_DIR}/zcl/zcl_control4_networking.c
	${ZB_STACK_DIR}/zcl/zcl_c_daily_schedule.c
	${ZB_STACK_DIR}/zcl/zcl_s_daily_schedule.c
	${ZB_STACK_DIR}/zcl/zcl_occupancy_sensing_commands.c
)