
/*
 * < CONFIG IC
 */
#ifndef CONFIG_WHC_HCI_IPC
#define CONFIG_AMEBADPLUS 1
#undef CONFIG_AMEBAGREEN2
#undef CONFIG_AMEBALITE
#define CALCULATE_FREE_TXBD 1
#define CLEAR_AVAIL_INT_BY_RD_TXBD 1
#endif
