ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_WHC_BRIDGE) += -DCONFIG_WHC_BRIDGE

ccflags-y += -DCONFIG_FULLMAC -DCONFIG_FULLMAC_HCI_SPI
ccflags-y += -I$(src)/../../common/netdev
ccflags-y += -I$(src)/../../bridge
ccflags-y += -I$(src)/../../common/include -I$(src)/.. -I$(src)/../../common -I$(src)/../../common/spi -I$(src)

bridge_spi-y := \
		../../common/spi/whc_spi_host_ops.o \
		../../common/spi/whc_spi_host_probe.o \
		../../common/netdev/whc_host_drv_probe.o \
		../../common/netdev/whc_host_ethtool_ops.o \
		../../common/netdev/whc_host_netdev_ops.o \
		../../common/whc_host_ops.o \
		../../common/whc_host_pkt_tx.o \
		../../common/whc_host_pkt_rx.o \
		../../common/whc_host_memory.o \
		../../common/whc_host_hci.o \
		../whc_bridge_host_tx.o \
		../whc_bridge_host_pkt_rx.o \
		../whc_bridge_host_netlink.o \
		../spi_bridge/whc_bridge_host_spi.o

obj-m += bridge_spi.o
