ccflags-$(CONFIG_AMEBADPLUS)           += -DCONFIG_AMEBADPLUS
ccflags-$(CONFIG_AMEBAGREEN2)          += -DCONFIG_AMEBAGREEN2
ccflags-$(CONFIG_AMEBALITE)            += -DCONFIG_AMEBALITE
ccflags-$(CONFIG_AMEBAX)               += -DCONFIG_AMEBAX

ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_IEEE80211R) += -DCONFIG_IEEE80211R
ccflags-$(CONFIG_WHC_HCI_USB) += -DCONFIG_WHC_HCI_USB
ccflags-$(CONFIG_WHC_CMD_PATH) += -DCONFIG_WHC_CMD_PATH
ccflags-$(CONFIG_WHC_WIFI_API_PATH) += -DCONFIG_WHC_WIFI_API_PATH
ccflags-$(CONFIG_SUPPLICANT_SME) += -DCONFIG_SUPPLICANT_SME
ccflags-$(CONFIG_FW_DOWNLOAD) += -DCONFIG_FW_DOWNLOAD
ccflags-$(CONFIG_WHCH) += -DCONFIG_WHCH

ccflags-y += -DCONFIG_WHC_HOST_LINUX
ccflags-y += -I$(src)/../netdev
ccflags-y += -I$(src)/../include -I$(src)/.. -I$(src)/../../common -I$(src)/../usb
ifeq ($(CONFIG_WHCH), y)
ccflags-y += -I$(src)/../whch -I$(src)/../whch/hal
ifeq ($(CONFIG_AMEBAGREEN2), y)
ccflags-y += -I$(src)/../whch/hal/rtl8721f
endif
endif

whc_usb-$(CONFIG_WHC_HCI_USB) := \
		../usb/whc_usb_host_ops.o \
		../usb/whc_usb_host_probe.o \
		../netdev/whc_host_ethtool_ops.o \
		../netdev/whc_host_netdev_ops.o \
		../whc_host_trx.o \
		../whc_host_pkt_tx.o \
		../whc_host_pkt_rx.o \
		../whc_host_memory.o \
		../whc_host_hci.o \
		../netdev/whc_host_ops_sta.o \
		../netdev/whc_host_wiphy.o \
		../whc_host_regd.o \
		../whc_host_ft.o \
		../netdev/whc_host_ops_ap.o \
		../netdev/whc_host_ops_key.o \
		../netdev/whc_host_ops_nan.o \
		../netdev/whc_host_ops_p2p.o \
		../netdev/whc_host_netdev_ops_p2p.o \
		../whc_host_cfgvendor.o \
		../whc_host_proc.o \
		../netdev/whc_host_ops.o \
			../whc_host_event_tx.o \
		../whc_host_event_rx.o \
		../whc_host_event_hdl.o \
		../whc_host_protocal_offload.o \
		../whc_host_acs.o

ifeq ($(CONFIG_WHCH), y)
    whc_usb-$(CONFIG_WHC_HCI_USB) += \
		../whch/whch_host_pkt_tx_proc.o \
		../whch/whch_host_pkt_rx_proc.o \
		../whch/whch_host_sta_mgt.o \
		../whch/whch_host_security.o \
		../whch/whch_host_arc4.o \
		../whch/whch_host_mlme.o \
		../whch/whch_host_addba.o \
		../whch/hal/whch_host_hal_xmit_com.o \
		../whch/hal/whch_host_hal_recv_com.o
ifeq ($(CONFIG_AMEBAGREEN2), y)
    whc_usb-$(CONFIG_WHC_HCI_USB) += \
		../whch/hal/rtl8721f/whch_host_hal_xmit.o \
		../whch/hal/rtl8721f/whch_host_hal_rate.o \
		../whch/hal/rtl8721f/whch_host_hal_recv.o
endif
endif

ifeq ($(CONFIG_WHC_CMD_PATH), y)
    whc_usb-$(CONFIG_WHC_HCI_USB) += \
            ../whc_host_netlink.o \
            ../whc_host_cmd_path_tx.o
endif

include $(src)/../fwdl/Kbuild
whc_usb-$(CONFIG_FW_DOWNLOAD) += $(addprefix ../fwdl/, $(FWDL_OBJS))

obj-m += whc_usb.o
