list(
    APPEND CSRC
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-13/tp_aps_bv-13_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-13/tp_aps_bv-13_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01C/tp_bdb_cn_nsa_tc_01c_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01D/tp_bdb_cn_nsa_tc_01d_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-04/tp_bdb_cs_nfs_tc_04_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03D/tp_bdb_dr_tar_tc_03d_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-05D/tp_bdb_dr_tar_tc_05d_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-CDP-TC-01/tp_bdb_fb_cdp_tc_01_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PIM-TC-01/tp_bdb_fb_pim_tc_01_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01A/tp_bdb_fb_pre_tc_01a_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01A/tp_bdb_fb_pre_tc_01a_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01B/tp_bdb_fb_pre_tc_01b_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01B/tp_bdb_fb_pre_tc_01b_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-02/tp_bdb_fb_pre_tc_02_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-02/tp_bdb_fb_pre_tc_02_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A/tp_bdb_fb_pre_tc_03a_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A/tp_bdb_fb_pre_tc_03a_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_26/tp_bdb_fb_pre_tc_03a_15_26_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_26/tp_bdb_fb_pre_tc_03a_15_26_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_27/tp_bdb_fb_pre_tc_03a_15_27_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_27/tp_bdb_fb_pre_tc_03a_15_27_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03B/tp_bdb_fb_pre_tc_03b_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03B/tp_bdb_fb_pre_tc_03b_the1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04A/tp_bdb_fb_pre_tc_04a_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04B/tp_bdb_fb_pre_tc_04b_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04C/tp_bdb_fb_pre_tc_04c_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-07/tp_bdb_fb_pre_tc_07_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-01/tp_nwk_bv-01_dutzed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-01/tp_nwk_bv-01_gzed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-06-I/tp_nwk_bv-06-i_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-06-I/tp_nwk_bv-06-i_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-07-I/tp_nwk_bv-07-i_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-07-I/tp_nwk_bv-07-i_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-08-I/tp_nwk_bv-08-i_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-1/tp_ped-1_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-10/tp_ped-10_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-11/tp_ped-11_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-12/tp_ped-12_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-13/tp_ped-13_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-14/tp_ped-14_gzed_var_ieee.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-2/tp_ped-2_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-2/tp_ped-2_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-3/tp_ped-3_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-3/tp_ped-3_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-4/tp_ped-4_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-5/tp_ped-5_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-6/tp_ped-6_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-7/tp_ped-7_gzed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-7/tp_ped-7_gzed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-8/tp_ped-8_thzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-9/tp_ped-9_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-02/tp_pro_bv_02_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-02/tp_pro_bv_02_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-03/tp_pro_bv_03_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-04/tp_pro_bv_04_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-12/tp_pro_bv_12_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-13/tp_pro_bv_13_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-17/tp_pro_bv_17_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-17/tp_pro_bv_17_zed4.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-28/tp_pro_bv_28_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-40/tp_pro_bv_40_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-01/tp_r20_bv-01_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-01/tp_r20_bv-01_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-02/tp_r20_bv-02_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-02/tp_r20_bv-02_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-03/tp_r20_bv-03_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-04/tp_r20_bv-04_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-05/tp_r20_bv-05_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-06/tp_r20_bv-06_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-07/tp_r20_bv-07_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-08/tp_r20_bv-08_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-09/tp_r20_bv-09_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-10/tp_r20_bv-10_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-11/tp_r20_bv-11_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-12/tp_r20_bv-12_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-14/tp_r20_bv-14_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-01/tp_r21_bv-01_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-02/tp_r21_bv-02_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-03/tp_r21_bv-03_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-04/tp_r21_bv_04_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-05/tp_r21_bv_05_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-06/tp_r21_bv-06_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-08/tp_r21_bv-08_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-09/tp_r21_bv-09_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-10/tp_r21_bv-10_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-11/tp_r21_bv-11_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-12/tp_r21_bv-12_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-13/tp_r21_bv-13_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-25/tp_r21_bv-25_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-27/tp_r21_bv-27_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-27/tp_r21_bv-27_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-28/tp_r21_bv-28_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-30/tp_r21_bv-30_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-30/tp_r21_bv-30_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R222_10_70/tp_r222_10_70_th_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R222_10_71/tp_r222_10_71_th_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-18/tp_r22_bv_18_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2462/tp_r22_ccb-2462_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2469/tp_r22_ccb-2469_dutzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2469/tp_r22_ccb-2469_gzed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-01/tp_r22_sgmb-01_gzsed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-01/tp_r22_sgmb-01_gzmed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-02/tp_r22_sgmb-02_dutzsed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-02/tp_r22_sgmb-02_dutzmed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-07/tp_r22_sgmb-07_gzsed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-07/tp_r22_sgmb-07_gzmed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-09/tp_r22_sgmb-09_dutzsed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-09/tp_r22_sgmb-09_dutzmed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-10/tp_r22_sgmb-10_dut_ed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-24-I/tp_sec_bv-24-i_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-25-I/tp_sec_bv-25-i_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-26-I/tp_sec_bv-26-i_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-27-I/tp_sec_bv-27-i_zed.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-28-I/tp_sec_bv-28-i_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-28-I/tp_sec_bv-28-i_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-29-I/tp_sec_bv-29-i_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-29-I/tp_sec_bv-29-i_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-03/tp_zdo_bv-03_gzed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-03/tp_zdo_bv-03_gzed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-04/tp_zdo_bv-04_dutzed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-04/tp_zdo_bv-04_gzed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-09/tp_zdo_bv-09_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-09/tp_zdo_bv-09_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-10/tp_zdo_bv-10_gzed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-10/tp_zdo_bv-10_gzed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-11/tp_zdo_bv-11_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-11/tp_zdo_bv-11_zed2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-12/tp_zdo_bv-12_zed1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-12/tp_zdo_bv-12_zed2.c
)