/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPCBASEDS_DATA_H_RPCGEN
#define _VOICERPCBASEDS_DATA_H_RPCGEN

#include <RPCBaseDS.h>

struct VOICE_RPC_INIT {
    int32_t voice_iface_flag;
    uint32_t mic_header_addr;
    long mic_header_length;
    uint32_t config_addr;
    long config_length;
    uint32_t usr_data;
};
typedef struct VOICE_RPC_INIT VOICE_RPC_INIT;

struct VOICE_RPC_RESULT {
    uint32_t usr_data;
    int32_t type;
    int32_t len;
    uint32_t msg_addr;
};
typedef struct VOICE_RPC_RESULT VOICE_RPC_RESULT;

struct VOICE_RPC_ERROR_STATE {
    long type;
    uint32_t data;
};
typedef struct VOICE_RPC_ERROR_STATE VOICE_RPC_ERROR_STATE;

#endif /* !_VOICERPCBASEDS_DATA_H_RPCGEN */
