/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPC_SYSTEM_H_RPCGEN
#define _VOICERPC_SYSTEM_H_RPCGEN

#include "rpc_struct.h"

#include "VoiceRPC_System_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VoiceRPCBaseDS.h>

#define VOICE_SYSTEM 3001
#define VERSION 0

struct REG_STRUCT * VOICE_SYSTEM_0_register(struct REG_STRUCT *rnode);
#define VOICE_RPC_ToAgent_Create 1
extern  HRESULT * VOICE_RPC_ToAgent_Create_0(VOICE_RPC_INIT *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToAgent_Create_0_svc(VOICE_RPC_INIT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToAgent_Create_0_svc)(VOICE_RPC_INIT *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToAgent_destroy 2
extern  HRESULT * VOICE_RPC_ToAgent_destroy_0(long *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToAgent_destroy_0_svc(long *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToAgent_destroy_0_svc)(long *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToAgent_Start 3
extern  HRESULT * VOICE_RPC_ToAgent_Start_0(long *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToAgent_Start_0_svc(long *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToAgent_Start_0_svc)(long *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_VOICERPC_SYSTEM_H_RPCGEN */
