/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <string.h> /* for memset */
#include <VoiceRPC_Agent.h>
#include <rpc_client.h>

#include <RPCBaseDS.h>
#include <VoiceRPCBaseDS.h>

HRESULT *
VOICE_RPC_ToSystem_Callback_0(VOICE_RPC_RESULT *argp, CLNT_STRUCT *clnt)
{
    RPC_STRUCT rpc;
    HRESULT * result = NULL ;
    long args_size = sizeof(VOICE_RPC_RESULT );


    // if NONBLOCK_MODE, dont need to alloc memory
    if (clnt->send_mode & BLOCK_MODE) {
        result = (HRESULT *) rpc_malloc(sizeof(HRESULT ));
    }


    // prepare the RPC call structure
    // including programID, versionID, TaskID...
    rpc = RPC_PrepareCall(clnt, (int)result);


    if (RPC_ClientCall (&rpc, VOICE_RPC_ToSystem_Callback, clnt->send_mode,
                        (xdrproc_t) xdr_VOICE_RPC_RESULT, (caddr_t) argp, args_size)
            != 0) {
        if(result)
            rpc_free(result);
        return (HRESULT *)-1;
    }


    //for blocking use
    if (clnt->send_mode & BLOCK_MODE) {
        XDR xdrs;

        WaitReply();
        xdrmem_create(&xdrs, (char *)result, sizeof(HRESULT), XDR_DECODE);
        if(!xdr_HRESULT(&xdrs, result))
            return (HRESULT *)-1;
        return result;
    }

    return 0;

}

HRESULT *
VOICE_RPC_ToSystem_State_0(VOICE_RPC_ERROR_STATE *argp, CLNT_STRUCT *clnt)
{
    RPC_STRUCT rpc;
    HRESULT * result = NULL ;
    long args_size = sizeof(VOICE_RPC_ERROR_STATE );


    // if NONBLOCK_MODE, dont need to alloc memory
    if (clnt->send_mode & BLOCK_MODE) {
        result = (HRESULT *) rpc_malloc(sizeof(HRESULT ));
    }


    // prepare the RPC call structure
    // including programID, versionID, TaskID...
    rpc = RPC_PrepareCall(clnt, (int)result);


    if (RPC_ClientCall (&rpc, VOICE_RPC_ToSystem_State, clnt->send_mode,
                        (xdrproc_t) xdr_VOICE_RPC_ERROR_STATE, (caddr_t) argp, args_size)
            != 0) {
        if(result)
            rpc_free(result);
        return (HRESULT *)-1;
    }


    //for blocking use
    if (clnt->send_mode & BLOCK_MODE) {
        XDR xdrs;

        WaitReply();
        xdrmem_create(&xdrs, (char *)result, sizeof(HRESULT), XDR_DECODE);
        if(!xdr_HRESULT(&xdrs, result))
            return (HRESULT *)-1;
        return result;
    }

    return 0;

}
