/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPC_AGENT_H_RPCGEN
#define _VOICERPC_AGENT_H_RPCGEN

#include "rpc_struct.h"

#include "VoiceRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VoiceRPCBaseDS.h>

#define VOICE_AGENT 3002
#define VERSION 0

struct REG_STRUCT * VOICE_AGENT_0_register(struct REG_STRUCT *rnode);
#define VOICE_RPC_ToSystem_Callback 1
extern  HRESULT * VOICE_RPC_ToSystem_Callback_0(VOICE_RPC_RESULT *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_Callback_0_svc(VOICE_RPC_RESULT *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_Callback_0_svc)(VOICE_RPC_RESULT *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToSystem_State 2
extern  HRESULT * VOICE_RPC_ToSystem_State_0(VOICE_RPC_ERROR_STATE *, CLNT_STRUCT *);
extern  HRESULT * VOICE_RPC_ToSystem_State_0_svc(VOICE_RPC_ERROR_STATE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT * (*p_VOICE_RPC_ToSystem_State_0_svc)(VOICE_RPC_ERROR_STATE *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_VOICERPC_AGENT_H_RPCGEN */
