/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPC_AGENT_DATA_H_RPCGEN
#define _VOICERPC_AGENT_DATA_H_RPCGEN

#include <RPCBaseDS.h>
#include <VoiceRPCBaseDS.h>

#endif /* !_VOICERPC_AGENT_DATA_H_RPCGEN */
