/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <VoiceRPCBaseDS.h>
#include <RPCBaseDS.h>

bool_t
xdr_VOICE_RPC_INIT (XDR *xdrs, VOICE_RPC_INIT *objp)
{
    if (!xdr_int32_t (xdrs, &objp->voice_iface_flag))
        return FALSE;
    if (!xdr_uint32_t (xdrs, &objp->mic_header_addr))
        return FALSE;
    if (!xdr_long (xdrs, &objp->mic_header_length))
        return FALSE;
    if (!xdr_uint32_t (xdrs, &objp->config_addr))
        return FALSE;
    if (!xdr_long (xdrs, &objp->config_length))
        return FALSE;
    if (!xdr_uint32_t (xdrs, &objp->usr_data))
        return FALSE;
    return TRUE;
}

bool_t
xdr_VOICE_RPC_RESULT (XDR *xdrs, VOICE_RPC_RESULT *objp)
{
    if (!xdr_uint32_t (xdrs, &objp->usr_data))
        return FALSE;
    if (!xdr_int32_t (xdrs, &objp->type))
        return FALSE;
    if (!xdr_int32_t (xdrs, &objp->len))
        return FALSE;
    if (!xdr_uint32_t (xdrs, &objp->msg_addr))
        return FALSE;
    return TRUE;
}

bool_t
xdr_VOICE_RPC_ERROR_STATE (XDR *xdrs, VOICE_RPC_ERROR_STATE *objp)
{
    if (!xdr_long (xdrs, &objp->type))
        return FALSE;
    if (!xdr_uint32_t (xdrs, &objp->data))
        return FALSE;
    return TRUE;
}
