ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_MCC) += -DCONFIG_MCC
ccflags-$(CONFIG_IEEE80211R) += -DCONFIG_IEEE80211R
ccflags-$(CONFIG_BT_INIC) += -DCONFIG_BT_INIC
ccflags-$(CONFIG_FULLMAC_HCI_SDIO) += -DCONFIG_FULLMAC_HCI_SDIO
ccflags-$(CONFIG_WHC_CMD_PATH) += -DCONFIG_WHC_CMD_PATH

ccflags-y += -DCONFIG_FULLMAC
ccflags-y += -I$(src)/../../common/netdev
ccflags-y += -I$(src)/../../common/include -I$(src)/.. -I$(src)/../../common -I$(src)/../../common/sdio

fullmac_sdio-$(CONFIG_FULLMAC_HCI_SDIO) := \
		../../common/sdio/whc_sdio_host_drvio.o \
		../../common/sdio/whc_sdio_host_ops.o \
		../../common/sdio/whc_sdio_host_probe.o \
		../../common/sdio/whc_sdio_host_init.o	\
		../../common/sdio/whc_sdio_host_fwdl.o	\
		../../common/netdev/whc_host_drv_probe.o \
		../../common/netdev/whc_host_ethtool_ops.o \
		../../common/netdev/whc_host_netdev_ops.o \
		../../common/whc_host_ops.o \
		../../common/whc_host_pkt_tx.o \
		../../common/whc_host_pkt_rx.o \
		../../common/whc_host_memory.o \
		../../common/whc_host_hci.o \
		../whc_fullmac_host_ops.o \
		../whc_fullmac_host_wiphy.o \
		../whc_fullmac_host_regd.o \
		../whc_fullmac_host_ft.o \
		../whc_fullmac_host_ops_ap.o \
		../whc_fullmac_host_ops_key.o \
		../whc_fullmac_host_ops_nan.o \
		../whc_fullmac_host_ops_p2p.o \
		../whc_fullmac_host_netdev_ops_p2p.o \
		../whc_fullmac_host_cfgvendor.o \
		../whc_fullmac_host_proc.o \
		../whc_fullmac_host_event_tx.o \
		../whc_fullmac_host_event_rx.o \
		../whc_fullmac_host_pkt_rx.o \
		../whc_fullmac_host_protocal_offload.o \
		../whc_fullmac_host_ioctl.o \
		../whc_fullmac_host_cust_evt.o \
		../whc_fullmac_host_acs.o

ifeq ($(CONFIG_WHC_CMD_PATH), y)
    fullmac_sdio-$(CONFIG_FULLMAC_HCI_SDIO) += \
            ../../common/whc_host_netlink.o \
            ../../common/whc_host_cmd_path_tx.o

    ifeq ($(CONFIG_WHC_WPA_OPS),y)
        ccflags-y += -I$(src)/../../common/wpa_ops_demo

        fullmac_sdio-$(CONFIG_FULLMAC_HCI_SDIO) += \
               ../../common/wpa_ops_demo/whc_wpa_ops_custom_netlink.o \
               ../../common/wpa_ops_demo/whc_wpa_ops_api.o
    endif

endif

fullmac_sdio-$(CONFIG_BT_INIC) += rtb_sdio.o

obj-m += fullmac_sdio.o
