ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_MCC) += -DCONFIG_MCC
ccflags-$(CONFIG_IEEE80211R) += -DCONFIG_IEEE80211R
ccflags-$(CONFIG_BT_INIC) += -DCONFIG_BT_INIC
ccflags-$(CONFIG_WHC_HCI_SDIO) += -DCONFIG_WHC_HCI_SDIO
ccflags-$(CONFIG_WHC_CMD_PATH) += -DCONFIG_WHC_CMD_PATH
ccflags-$(CONFIG_WHC_WIFI_API_PATH) += -DCONFIG_WHC_WIFI_API_PATH
ccflags-$(CONFIG_WHC_ACTIVE_DETECT) += -DCONFIG_WHC_ACTIVE_DETECT
ccflags-$(CONFIG_SUPPLICANT_SME) += -DCONFIG_SUPPLICANT_SME
ccflags-$(CONFIG_RMESH) += -DCONFIG_RMESH
ccflags-$(CONFIG_FW_DOWNLOAD) += -DCONFIG_FW_DOWNLOAD
ccflags-$(CONFIG_WHCH) += -DCONFIG_WHCH

ccflags-y += -DCONFIG_FULLMAC
ccflags-y += -I$(src)/../netdev
ccflags-y += -I$(src)/../include -I$(src)/.. -I$(src)/../../common -I$(src)/../sdio

ifeq ($(CONFIG_WHCH), y)
ccflags-y += -I$(src)/../whch -I$(src)/../whch/hal
ifeq ($(CONFIG_WHC_HAL_CHIP), rtl8721f)
ccflags-y += -I$(src)/../whch/hal/rtl8721f
endif
endif

#for ko size, no debug info if enabled
#EXTRA_CFLAGS += -g0

whc_sdio-$(CONFIG_WHC_HCI_SDIO) := \
		../sdio/whc_sdio_host_drvio.o \
		../sdio/whc_sdio_host_ops.o \
		../sdio/whc_sdio_host_probe.o \
		../sdio/whc_sdio_host_init.o	\
		../netdev/whc_host_ethtool_ops.o \
		../netdev/whc_host_netdev_ops.o \
		../whc_host_trx.o \
		../whc_host_pkt_tx.o \
		../whc_host_pkt_rx.o \
		../whc_host_memory.o \
		../whc_host_hci.o \
		../whc_host_ft.o \
		../whc_host_ops_nan.o \
		../whc_host_ops_p2p.o \
		../whc_host_netdev_ops_p2p.o \
		../whc_host_cfgvendor.o \
		../whc_host_ioctl.o \
		../whc_host_cust_evt.o

ifeq ($(CONFIG_WHCH), y)
    whc_sdio-$(CONFIG_WHC_HCI_SDIO) += \
		../whch/whch_host_pkt_tx_proc.o \
		../whch/whch_host_pkt_rx_proc.o \
		../whch/whch_host_sta_mgt.o \
		../whch/whch_host_security.o \
		../whch/whch_host_mlme.o \
		../whch/whch_host_addba.o \
		../whch/hal/whch_host_hal_xmit_com.o \
		../whch/hal/whch_host_hal_recv_com.o
ifeq ($(CONFIG_WHC_HAL_CHIP), rtl8721f)
    whc_sdio-$(CONFIG_WHC_HCI_SDIO) += \
		../whch/hal/rtl8721f/whch_host_hal_xmit.o \
		../whch/hal/rtl8721f/whch_host_hal_rate.o \
		../whch/hal/rtl8721f/whch_host_hal_recv.o
endif
endif

ifeq ($(CONFIG_WHC_WIFI_API_PATH), y)
    whc_sdio-$(CONFIG_WHC_HCI_SDIO) += \
			../whc_host_proc.o \
			../whc_host_ops.o \
			../whc_host_ops_ap.o \
			../whc_host_event_tx.o \
			../whc_host_event_rx.o \
			../whc_host_wiphy.o \
			../whc_host_regd.o \
			../whc_host_protocal_offload.o \
			../whc_host_ops_key.o \
			../whc_host_acs.o

endif

ifeq ($(CONFIG_WHC_CMD_PATH), y)
    whc_sdio-$(CONFIG_WHC_HCI_SDIO) += \
            ../whc_host_netlink.o \
            ../whc_host_cmd_path_tx.o

    ifeq ($(CONFIG_WHC_HOST_RTW_CLI),y)
        ccflags-$(CONFIG_WHC_HOST_RTW_CLI) += -DCONFIG_WHC_HOST_RTW_CLI
        ccflags-y += -I$(src)/../whc_host_rtw_cli

        whc_sdio-$(CONFIG_WHC_HCI_SDIO) += \
               ../whc_host_rtw_cli/whc_host_rtw_cli_custom_netlink.o \
               ../whc_host_rtw_cli/whc_host_rtw_cli_api.o
    endif

endif

whc_sdio-$(CONFIG_BT_INIC) += rtb_sdio.o

include $(src)/../fwdl/Kbuild
whc_sdio-$(CONFIG_FW_DOWNLOAD) += $(addprefix ../fwdl/, $(FWDL_OBJS))

obj-m += whc_sdio.o
