export CONFIG_AMEBADPLUS = y

ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_IEEE80211R) += -DCONFIG_IEEE80211R
ccflags-$(CONFIG_FULLMAC_HCI_USB) += -DCONFIG_FULLMAC_HCI_USB
ccflags-$(CONFIG_WHC_WIFI_API_PATH) += -DCONFIG_WHC_WIFI_API_PATH

ccflags-y += -DCONFIG_FULLMAC
ccflags-y += -I$(src)/../../common/netdev
ccflags-y += -I$(src)/../../common/include -I$(src)/.. -I$(src)/../../common -I$(src)/../../common/usb

fullmac_usb-$(CONFIG_FULLMAC_HCI_USB) := \
		../../common/usb/whc_usb_host_ops.o \
		../../common/usb/whc_usb_host_probe.o \
		../../common/netdev/whc_host_drv_probe.o \
		../../common/netdev/whc_host_ethtool_ops.o \
		../../common/netdev/whc_host_netdev_ops.o \
		../../common/whc_host_ops.o \
		../../common/whc_host_pkt_tx.o \
		../../common/whc_host_pkt_rx.o \
		../../common/whc_host_memory.o \
		../../common/whc_host_hci.o \
		../whc_fullmac_host_ops.o \
		../whc_fullmac_host_wiphy.o \
		../whc_fullmac_host_regd.o \
		../whc_fullmac_host_ft.o \
		../whc_fullmac_host_ops_ap.o \
		../whc_fullmac_host_ops_key.o \
		../whc_fullmac_host_ops_nan.o \
		../whc_fullmac_host_ops_p2p.o \
		../whc_fullmac_host_netdev_ops_p2p.o \
		../whc_fullmac_host_cfgvendor.o \
		../whc_fullmac_host_proc.o \
		../whc_fullmac_host_event_tx.o \
		../whc_fullmac_host_event_rx.o \
		../whc_fullmac_host_pkt_rx.o \
		../whc_fullmac_host_protocal_offload.o \
		../whc_fullmac_host_ioctl.o \
		../whc_fullmac_host_cust_evt.o \
		../whc_fullmac_host_acs.o

obj-m += fullmac_usb.o
