ccflags-$(CONFIG_NAN) += -DCONFIG_NAN
ccflags-$(CONFIG_P2P) += -DCONFIG_P2P
ccflags-$(CONFIG_SDIO_BRIDGE) += -DCONFIG_SDIO_BRIDGE
ccflags-y += -DCONFIG_FULLMAC -DCONFIG_FULLMAC_HCI_SDIO
ccflags-y += -I$(src)/../include -I$(src)/.. -I$(src) -I$(src)/../common

bridge_sdio-y := ../sdio/rtw_sdio_drvio.o \
		../sdio/rtw_sdio_ops.o \
		../sdio/rtw_sdio_probe.o \
		../rtw_drv_probe.o \
		../rtw_ethtool_ops.o \
		../rtw_netdev_ops.o \
		../rtw_proc.o \
		../common/rtw_llhw_ops.o \
		../common/rtw_llhw_event.o \
		../common/rtw_llhw_recv.o \
		../common/rtw_llhw_xmit.o \
		../common/rtw_llhw_hci.o \
		../common/rtw_llhw_memory.o \
		rtw_sdio_bridge.o

obj-m += bridge_sdio.o
