#include "ameba_soc.h"

#include "bsp_mcu_com.h"
#include "bsp_mcu_ili9806.h"

void ILI9806_Init(void)
{
	DiagPrintf("ILI9806 Init FLOW ...... \n");

	/* ILI9806 Reset Pin config for ILI9806_Init */
	GPIO_InitTypeDef GPIO_InitStruct_RST;
	GPIO_InitStruct_RST.GPIO_Pin = MCU_RESET_PIN;
	GPIO_InitStruct_RST.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(&GPIO_InitStruct_RST);

	/* Reset */
	GPIO_WriteBit(MCU_RESET_PIN, 1);
	DelayMs(2);

	GPIO_WriteBit(MCU_RESET_PIN, 0);
	DelayMs(10);

	GPIO_WriteBit(MCU_RESET_PIN, 1);
	DelayMs(120);

	//************* Start Initial Sequence(ILI9906) **********//
	/***************************************/

	LCD_WR_REG(0xFF); // EXTC Command Set enable register
	LCD_WR_DATA(0xFF);
	LCD_WR_DATA(0x98);
	LCD_WR_DATA(0x06);

	//LCD_WR_REG(0xBA);//SPI Interface Setting
	//LCD_WR_DATA(0x60);

	LCD_WR_REG(0xBC); // GIP 1
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x0F);
	LCD_WR_DATA(0x61);
	LCD_WR_DATA(0xFF);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x0B);
	LCD_WR_DATA(0x10);
	LCD_WR_DATA(0x37);
	LCD_WR_DATA(0x63);
	LCD_WR_DATA(0xFF);
	LCD_WR_DATA(0xFF);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0xFF);
	LCD_WR_DATA(0x52);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x40);

	LCD_WR_REG(0xBD); // GIP 2
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x23);
	LCD_WR_DATA(0x45);
	LCD_WR_DATA(0x67);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0x23);
	LCD_WR_DATA(0x45);
	LCD_WR_DATA(0x67);

	LCD_WR_REG(0xBE); // GIP 3
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0xAB);
	LCD_WR_DATA(0x60);
	LCD_WR_DATA(0x22);
	LCD_WR_DATA(0x22);
	LCD_WR_DATA(0x22);
	LCD_WR_DATA(0x22);
	LCD_WR_DATA(0x22);

	LCD_WR_REG(0xC7); // VCOM Control
	LCD_WR_DATA(0x36);

	LCD_WR_REG(0xED); // EN_volt_reg	 VGMP / VGMN /VGSP / VGSN voltage to output
	LCD_WR_DATA(0x7F);
	LCD_WR_DATA(0x0F);

	LCD_WR_REG(0XC0); // Power Control 1	Setting AVDD / AVEE / VGH / VGL
	LCD_WR_DATA(0x0F);
	LCD_WR_DATA(0x0B);
	LCD_WR_DATA(0x0A);//VGH 15V,VGLO-10V

	LCD_WR_REG(0XFC); //AVDD / AVEE generated by internal pumping.
	LCD_WR_DATA(0x08);

	LCD_WR_REG(0XDF);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x20);

	LCD_WR_REG(0XF3);//DVDD Voltage Setting
	LCD_WR_DATA(0x74);

	LCD_WR_REG(0xB4); // Inversion Type
	LCD_WR_DATA(0x00);//02
	LCD_WR_DATA(0x00);//02
	LCD_WR_DATA(0x00);//02

	LCD_WR_REG(0xF7); // Resolution Control
	LCD_WR_DATA(0x82);//480*800

	LCD_WR_REG(0xB1); // FRAME RATE Setting
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x13);
	LCD_WR_DATA(0x13);

	LCD_WR_REG(0XF2); //	CR_EQ_PC_SDT  #C0,06,40,28
	LCD_WR_DATA(0x80);
	LCD_WR_DATA(0x04);
	LCD_WR_DATA(0x40);
	LCD_WR_DATA(0x28);

	LCD_WR_REG(0XC1); // Power Control 2	 SD OP Bias_VRH1_VRH2_EXT_CPCK_SEL
	LCD_WR_DATA(0x17);
	LCD_WR_DATA(0x88);//VGMP
	LCD_WR_DATA(0x88);//VGMN
	LCD_WR_DATA(0x20);

	LCD_WR_REG(0xE0);   //Positive Gamma Control
	LCD_WR_DATA(0x00); //P1
	LCD_WR_DATA(0x0A); //P2
	LCD_WR_DATA(0x12); //P3
	LCD_WR_DATA(0x10); //P4
	LCD_WR_DATA(0x0E); //P5
	LCD_WR_DATA(0x20); //P6
	LCD_WR_DATA(0xCC); //P7
	LCD_WR_DATA(0x07); //P8
	LCD_WR_DATA(0x06); //P9
	LCD_WR_DATA(0x0B); //P10
	LCD_WR_DATA(0x0E); //P11
	LCD_WR_DATA(0x0F); //P12
	LCD_WR_DATA(0x0D); //P13
	LCD_WR_DATA(0x15); //P14
	LCD_WR_DATA(0x10); //P15
	LCD_WR_DATA(0x00); //P16

	LCD_WR_REG(0xE1); //Negative Gamma Correction
	LCD_WR_DATA(0x00); //P1
	LCD_WR_DATA(0x0B); //P2
	LCD_WR_DATA(0x13); //P3
	LCD_WR_DATA(0x0D); //P4
	LCD_WR_DATA(0x0E); //P5
	LCD_WR_DATA(0x1B); //P6
	LCD_WR_DATA(0x71); //P7
	LCD_WR_DATA(0x06); //P8
	LCD_WR_DATA(0x06); //P9
	LCD_WR_DATA(0x0A); //P10
	LCD_WR_DATA(0x0F); //P11
	LCD_WR_DATA(0x0E); //P12
	LCD_WR_DATA(0x0F); //P13
	LCD_WR_DATA(0x15); //P14
	LCD_WR_DATA(0x0C); //P15
	LCD_WR_DATA(0x00); //P16

	LCD_WR_REG(0x2a);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x01);
	LCD_WR_DATA(0xdf);

	LCD_WR_REG(0x2b);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x03);
	LCD_WR_DATA(0x1f);

	LCD_WR_REG(0x3A); // Pixel Format
	// LCD_WR_DATA(0x55);	//16bpp -- rgb565
	LCD_WR_DATA(0x77);		//24bpp -- rgb888

	LCD_WR_REG(0x36); //Memory Access Control
	LCD_WR_DATA(0x00); //02-180

	LCD_WR_REG(0x11);// Sleep out
	DelayMs(120);
	LCD_WR_REG(0x29);  //Display on
	DelayMs(20);
	LCD_WR_REG(0x2C);
}

void ILI9806_IFbitmode_Config(u32 BitMode)
{
	RTK_LOGI(NOTAG, "[ILI9806_IFbitmode_Config] BitMode:%lu (0:8-bit, 2:16-bit, 4:24-bit)\r\n", BitMode);

	/* IM[3:0] Init*/
	GPIO_InitTypeDef GPIO_InitStruct_IM3;
	GPIO_InitStruct_IM3.GPIO_Pin = MCU_IM3_PIN;
	GPIO_InitStruct_IM3.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(&GPIO_InitStruct_IM3);

	GPIO_InitTypeDef GPIO_InitStruct_IM2;
	GPIO_InitStruct_IM2.GPIO_Pin = MCU_IM2_PIN;
	GPIO_InitStruct_IM2.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(&GPIO_InitStruct_IM2);

	GPIO_InitTypeDef GPIO_InitStruct_IM1;
	GPIO_InitStruct_IM1.GPIO_Pin = MCU_IM1_PIN;
	GPIO_InitStruct_IM1.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(&GPIO_InitStruct_IM1);

	GPIO_InitTypeDef GPIO_InitStruct_IM0;
	GPIO_InitStruct_IM0.GPIO_Pin = MCU_IM0_PIN;
	GPIO_InitStruct_IM0.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_Init(&GPIO_InitStruct_IM0);

	switch (BitMode) {
	case ILI9806_MCU_Parallel_8b_0000:
		GPIO_WriteBit(MCU_IM3_PIN, 0);
		GPIO_WriteBit(MCU_IM2_PIN, 0);
		GPIO_WriteBit(MCU_IM1_PIN, 0);
		GPIO_WriteBit(MCU_IM0_PIN, 0);
		RTK_LOGI(NOTAG, "ILI9806_MCU_Parallel_8b_0000 \r\n");
		lcd_dev.McuLcdBitMode = MCU_LCD_8BIT_IF;
		break;

	case ILI9806_MCU_Parallel_16b_0001:
		GPIO_WriteBit(MCU_IM3_PIN, 0);
		GPIO_WriteBit(MCU_IM2_PIN, 0);
		GPIO_WriteBit(MCU_IM1_PIN, 0);
		GPIO_WriteBit(MCU_IM0_PIN, 1);
		RTK_LOGI(NOTAG, "ILI9806_MCU_Parallel_16b_0001 \r\n");
		lcd_dev.McuLcdBitMode = MCU_LCD_16BIT_IF;
		break;

	case ILI9806_MCU_Parallel_24b_0010:
		GPIO_WriteBit(MCU_IM3_PIN, 0);
		GPIO_WriteBit(MCU_IM2_PIN, 0);
		GPIO_WriteBit(MCU_IM1_PIN, 1);
		GPIO_WriteBit(MCU_IM0_PIN, 0);
		RTK_LOGI(NOTAG, "ILI9806_MCU_Parallel_24b_0010 \r\n");
		lcd_dev.McuLcdBitMode = MCU_LCD_24BIT_IF;
		break;

	default:
		RTK_LOGI(NOTAG, "Unknown ILI9806_MCU_Parallel_xbits !!! \r\n");
		break;
	}
}