
set(c_AXF2BIN_SCRIPT        ${c_BASEDIR}/tools/scripts/axf2bin.py)
set(c_AXF2BIN_RUN python    ${c_AXF2BIN_SCRIPT})
set(op_USAGE                ${c_AXF2BIN_RUN} -h)
set(op_PREPEND_HEADER       ${c_AXF2BIN_RUN} prepend_header)
set(op_OTA_PREPEND_HEADER   ${c_AXF2BIN_RUN} ota_prepend_header )
set(op_PAD                  ${c_AXF2BIN_RUN} pad)
set(op_FW_PACKAGE           ${c_AXF2BIN_RUN} fw_pack)
set(op_COMPRESS             ${c_AXF2BIN_RUN} compress)
set(op_PAD_BINARY           ${c_AXF2BIN_RUN} pad_binary)
set(op_CUT                  ${c_AXF2BIN_RUN} cut)
