
ifeq ($(CONFIG_AMEBALITE), y)
vpath %.c $(DIR)/phy_g6/rf \
		$(DIR)/phy_g6/rf/halrf_8720e \
		$(DIR)/phy_g6/bb \
		$(DIR)/phy_g6/bb/halbb_8720e \

CONFIG_PHY_G6 = y

endif

ifeq ($(CONFIG_AMEBADPLUS), y)
vpath %.c $(DIR)/phydm \
		$(DIR)/phydm/rtl8721da \
		$(DIR)/phydm/halrf \
		$(DIR)/phydm/halrf/rtl8721da \
		
CONFIG_PHYDM = y

endif

ifeq ($(CONFIG_AMEBASMART), y)
vpath %.c $(DIR)/phy_g6 \
		$(DIR)/phy_g6/bb \
		$(DIR)/phy_g6/bb/halbb_8730e \
		$(DIR)/phy_g6/rf \
		$(DIR)/phy_g6/rf/halrf_8730e

CONFIG_PHY_G6 = y

endif

ifeq ($(CONFIG_AMEBAGREEN2), y)
vpath %.c $(DIR)/phy_g6 \
		$(DIR)/phy_g6/bb \
		$(DIR)/phy_g6/bb/halbb_8720f \
		$(DIR)/phy_g6/rf \
		$(DIR)/phy_g6/rf/halrf_8720f

CONFIG_PHY_G6 = y

endif

ifeq ($(CONFIG_PHYDM), y)

CSRC_PHY +=  \
	$(DIR)/phydm/phydm_debug.c \
	$(DIR)/phydm/phydm_dynamictxpower.c \
	$(DIR)/phydm/phydm_interface.c \
	$(DIR)/phydm/phydm_primary_cca.c \
	$(DIR)/phydm/phydm_psd.c \
	$(DIR)/phydm/phydm_rssi_monitor.c \
	$(DIR)/phydm/phydm.c \
	$(DIR)/phydm/phydm_adc_sampling.c \
	$(DIR)/phydm/phydm_api.c \
	$(DIR)/phydm/phydm_ccx.c \
	$(DIR)/phydm/phydm_dfs.c \
	$(DIR)/phydm/phydm_hwconfig.c \
	$(DIR)/phydm/phydm_pmac_tx_setting.c \
	$(DIR)/phydm/phydm_mp.c

CSRC_PHY += $(DIR)/phydm/halrf/halrf.c \
	$(DIR)/phydm/halrf/halrf_debug.c \
	$(DIR)/phydm/halrf/halphyrf_iot.c \
	$(DIR)/phydm/halrf/halrf_kfree.c \
	$(DIR)/phydm/halrf/halrf_powertracking.c \
	$(DIR)/phydm/halrf/halrf_powertracking_iot.c \
	$(DIR)/phydm/halrf/halrf_psd.c \

CSRC_PHY += $(DIR)/phydm/phydm_cfotracking.c \
	$(DIR)/phydm/phydm_math_lib.c \
	$(DIR)/phydm/phydm_phystatus.c \
	$(DIR)/phydm/phydm_ch_info.c \


endif

ifeq ($(CONFIG_PHY_G6), y)
#halbb
path_halbb_d1 := $(DIR)/phy_g6/bb
CSRC_PHY += $(path_halbb_d1)/halbb.o \
	$(path_halbb_d1)/halbb_api.o \
	$(path_halbb_d1)/halbb_cfo_trk.o \
	$(path_halbb_d1)/halbb_ch_info.o \
	$(path_halbb_d1)/halbb_cmn_rpt.o \
	$(path_halbb_d1)/halbb_cmn_rpt_dbg.o \
	$(path_halbb_d1)/halbb_dbg.o \
	$(path_halbb_d1)/halbb_dbg_cmd.o \
	$(path_halbb_d1)/halbb_dfs.o \
	$(path_halbb_d1)/halbb_env_mntr.o \
	$(path_halbb_d1)/halbb_hw_cfg.o \
	$(path_halbb_d1)/halbb_init.o \
	$(path_halbb_d1)/halbb_interface.o \
	$(path_halbb_d1)/halbb_la_mode.o \
	$(path_halbb_d1)/halbb_math_lib.o \
	$(path_halbb_d1)/halbb_mp.o \
	$(path_halbb_d1)/halbb_plcp_gen.o \
	$(path_halbb_d1)/halbb_plcp_tx.o \
	$(path_halbb_d1)/halbb_pmac_setting.o \
	$(path_halbb_d1)/halbb_psd.o \
	$(path_halbb_d1)/halbb_physts.o \
	$(path_halbb_d1)/halbb_pwr_ctrl.o \
	$(path_halbb_d1)/halbb_statistics.o \
	$(path_halbb_d1)/halbb_spur_suppress.o

#halrf
path_halrf_d1 := $(DIR)/phy_g6/rf
CSRC_PHY += $(path_halrf_d1)/halrf.o \
	$(path_halrf_d1)/halrf_pmac.o \
	$(path_halrf_d1)/halrf_api.o \
	$(path_halrf_d1)/halrf_dbg.o \
	$(path_halrf_d1)/halrf_dbg_cmd.o \
	$(path_halrf_d1)/halrf_hw_cfg.o \
	$(path_halrf_d1)/halrf_init.o \
	$(path_halrf_d1)/halrf_interface.o \
	$(path_halrf_d1)/halrf_pwr_table.o \
	$(path_halrf_d1)/halrf_iqk.o


endif

ifeq ($(CONFIG_AMEBALITE), y)

path_halbb_8720e := $(path_halbb_d1)/halbb_8720e
CSRC_PHY += $(path_halbb_8720e)/halbb_8720e.o \
	$(path_halbb_8720e)/halbb_8720e_api.o \
	$(path_halbb_8720e)/halbb_hwimg_8720e.o \
	$(path_halbb_8720e)/halbb_reg_cfg_8720e.o

path_halrf_8720e := $(path_halrf_d1)/halrf_8720e
CSRC_PHY += $(path_halrf_8720e)/halrf_8720e.o \
	$(path_halrf_8720e)/halrf_8720e_api.o \
	$(path_halrf_8720e)/halrf_hwimg_8720e.o\
	$(path_halrf_8720e)/halrf_iqk_8720e.o\
	$(path_halrf_8720e)/halrf_reg_cfg_8720e.o\
	$(path_halrf_8720e)/halrf_dpk_8720e.o\
	$(path_halrf_8720e)/halrf_txgapk_8720e.o\
	$(path_halrf_8720e)/halrf_dack_8720e.o\
	$(path_halrf_8720e)/halrf_set_pwr_table_8720e.o\
	$(path_halrf_8720e)/halrf_tssi_8720e.o\
	$(path_halrf_8720e)/halrf_kfree_8720e.o\
	$(path_halrf_8720e)/halrf_psd_8720e.o

endif

ifeq ($(CONFIG_AMEBADPLUS), y)

CSRC_PHY += $(DIR)/phydm/rtl8721da/halhwimg_bb.c \
	$(DIR)/phydm/rtl8721da/phydm_hal_api8721da.c \
	$(DIR)/phydm/rtl8721da/phydm_regconfig8721da.c

CSRC_PHY += $(DIR)/phydm/halrf/rtl8721da/halrf_8721da.c \
	$(DIR)/phydm/halrf/rtl8721da/halhwimg_rf.c \
	$(DIR)/phydm/halrf/rtl8721da/halrf_iqk_8721da.c \
	$(DIR)/phydm/halrf/rtl8721da/halrf_dpk_8721da.c \
	$(DIR)/phydm/halrf/rtl8721da/halrf_rfk_init_8721da.c \
	$(DIR)/phydm/halrf/rtl8721da/halrf_txgapk_8721da.c \

endif

ifeq ($(CONFIG_AMEBASMART), y)

path_halbb_8730e := $(path_halbb_d1)/halbb_8730e
CSRC_PHY += $(path_halbb_8730e)/halbb_8730e.o \
	$(path_halbb_8730e)/halbb_8730e_api.o \
	$(path_halbb_8730e)/halbb_hwimg_8730e.o \
	$(path_halbb_8730e)/halbb_reg_cfg_8730e.o

path_halrf_8730e := $(path_halrf_d1)/halrf_8730e
CSRC_PHY += $(path_halrf_8730e)/halrf_8730e.o \
	$(path_halrf_8730e)/halrf_8730e_api.o \
	$(path_halrf_8730e)/halrf_hwimg_8730e.o\
	$(path_halrf_8730e)/halrf_iqk_8730e.o\
	$(path_halrf_8730e)/halrf_reg_cfg_8730e.o\
	$(path_halrf_8730e)/halrf_dpk_8730e.o\
	$(path_halrf_8730e)/halrf_txgapk_8730e.o\
	$(path_halrf_8730e)/halrf_dack_8730e.o\
	$(path_halrf_8730e)/halrf_set_pwr_table_8730e.o\
	$(path_halrf_8730e)/halrf_tssi_8730e.o\
	$(path_halrf_8730e)/halrf_kfree_8730e.o\
	$(path_halrf_8730e)/halrf_psd_8730e.o

endif

ifeq ($(CONFIG_AMEBAGREEN2), y)

path_halbb_8720f := $(path_halbb_d1)/halbb_8720f
CSRC_PHY += $(path_halbb_8720f)/halbb_8720f.o \
	$(path_halbb_8720f)/halbb_8720f_api.o \
	$(path_halbb_8720f)/halbb_hwimg_8720f.o \
	$(path_halbb_8720f)/halbb_hwimg_bcnmode_8720f.o \
	$(path_halbb_8720f)/halbb_reg_cfg_8720f.o

path_halrf_8720f := $(path_halrf_d1)/halrf_8720f
CSRC_PHY += $(path_halrf_8720f)/halrf_8720f.o \
	$(path_halrf_8720f)/halrf_8720f_api.o \
	$(path_halrf_8720f)/halrf_hwimg_8720f.o\
	$(path_halrf_8720f)/halrf_iqk_8720f.o\
	$(path_halrf_8720f)/halrf_reg_cfg_8720f.o\
	$(path_halrf_8720f)/halrf_dpk_8720f.o\
	$(path_halrf_8720f)/halrf_txgapk_8720f.o\
	$(path_halrf_8720f)/halrf_dack_8720f.o\
	$(path_halrf_8720f)/halrf_set_pwr_table_8720f.o\
	$(path_halrf_8720f)/halrf_tssi_8720f.o\
	$(path_halrf_8720f)/halrf_kfree_8720f.o\
	$(path_halrf_8720f)/halrf_psd_8720f.o

endif

OBJS_PHY = $(notdir $(CSRC_PHY:.c=.o))

make_objs_phy: GLOBAL_CFLAGS += -DCOMPIL_LOG_LEVEL=RTK_LOG_INFO
make_objs_phy: $(OBJS_PHY)
