list(
    APPEND CSRC
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-13/tp_aps_bv-13_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-13/tp_aps_bv-13_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-14-I/tp_aps_bv_14_i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-14-I/tp_aps_bv_14_i_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-14-I/tp_aps_bv_14_i_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-15-I/tp_aps_bv-15-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-15-I/tp_aps_bv-15-i_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-15-I/tp_aps_bv-15-i_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-16-I/tp_aps_bv-16-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-16-I/tp_aps_bv-16-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-17-I/tp_aps_bv-17-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-17-I/tp_aps_bv-17-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-18-I/tp_aps_bv-18-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-18-I/tp_aps_bv-18-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-19-I/tp_aps_bv-19-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-19-I/tp_aps_bv-19-i_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-19-I/tp_aps_bv-19-i_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-20-I/tp_aps_bv-20-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-20-I/tp_aps_bv-20-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-23-I/tp_aps_bv-23-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-23-I/tp_aps_bv-23-i_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-23-I/tp_aps_bv-23-i_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_APS_BV-23-I/tp_aps_bv-23-i_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01C/tp_bdb_cn_nsa_tc_01c_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01C/tp_bdb_cn_nsa_tc_01c_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01C/tp_bdb_cn_nsa_tc_01c_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01D/tp_bdb_cn_nsa_tc_01d_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01D/tp_bdb_cn_nsa_tc_01d_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01D/tp_bdb_cn_nsa_tc_01d_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CN-NSA-TC-01D/tp_bdb_cn_nsa_tc_01d_thr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-04/tp_bdb_cs_nfs_tc_04_dut.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-04/tp_bdb_cs_nfs_tc_04_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-04/tp_bdb_cs_nfs_tc_04_thr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-05A/tp_bdb_cs_nfs_tc_05a_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-05A/tp_bdb_cs_nfs_tc_05a_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-05B/tp_bdb_cs_nfs_tc_05b_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-NFS-TC-05B/tp_bdb_cs_nfs_tc_05b_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-TCP-TC-01B/tp_bdb_cs_tcp_tc_01b_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-TCP-TC-01B/tp_bdb_cs_tcp_tc_01b_gzr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_CS-TCP-TC-01B/tp_bdb_cs_tcp_tc_01b_gzr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03C/tp_bdb_dr_tar_tc_03c_dut.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03C/tp_bdb_dr_tar_tc_03c_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03D/tp_bdb_dr_tar_tc_03d_thc1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03D/tp_bdb_dr_tar_tc_03d_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03E/tp_bdb_dr_tar_tc_03e_dut.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03E/tp_bdb_dr_tar_tc_03e_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-03E/tp_bdb_dr_tar_tc_03e_thr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-05C/tp_bdb_dr_tar_tc_05c_dut.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-05C/tp_bdb_dr_tar_tc_05c_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-05D/tp_bdb_dr_tar_tc_05d_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-05D/tp_bdb_dr_tar_tc_05d_thc1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_DR-TAR-TC-05D/tp_bdb_dr_tar_tc_05d_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-CDP-TC-01/tp_bdb_fb_cdp_tc_01_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-CDP-TC-01/tp_bdb_fb_cdp_tc_01_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-CDP-TC-01/tp_bdb_fb_cdp_tc_01_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-CDP-TC-01/tp_bdb_fb_cdp_tc_01_thr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PIM-TC-01/tp_bdb_fb_pim_tc_01_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PIM-TC-01/tp_bdb_fb_pim_tc_01_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PIM-TC-01/tp_bdb_fb_pim_tc_01_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01A/tp_bdb_fb_pre_tc_01a_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01A/tp_bdb_fb_pre_tc_01a_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01A/tp_bdb_fb_pre_tc_01a_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01A/tp_bdb_fb_pre_tc_01a_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01B/tp_bdb_fb_pre_tc_01b_thc1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01B/tp_bdb_fb_pre_tc_01b_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-01B/tp_bdb_fb_pre_tc_01b_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-02/tp_bdb_fb_pre_tc_02_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-02/tp_bdb_fb_pre_tc_02_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-02/tp_bdb_fb_pre_tc_02_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A/tp_bdb_fb_pre_tc_03a_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A/tp_bdb_fb_pre_tc_03a_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A/tp_bdb_fb_pre_tc_03a_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_26/tp_bdb_fb_pre_tc_03a_15_26_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_26/tp_bdb_fb_pre_tc_03a_15_26_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_26/tp_bdb_fb_pre_tc_03a_15_26_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_27/tp_bdb_fb_pre_tc_03a_15_27_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_27/tp_bdb_fb_pre_tc_03a_15_27_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03A_15_27/tp_bdb_fb_pre_tc_03a_15_27_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03B/tp_bdb_fb_pre_tc_03b_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03B/tp_bdb_fb_pre_tc_03b_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-03B/tp_bdb_fb_pre_tc_03b_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04A/tp_bdb_fb_pre_tc_04a_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04A/tp_bdb_fb_pre_tc_04a_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04A/tp_bdb_fb_pre_tc_04a_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04B/tp_bdb_fb_pre_tc_04b_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04B/tp_bdb_fb_pre_tc_04b_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04B/tp_bdb_fb_pre_tc_04b_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04C/tp_bdb_fb_pre_tc_04c_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04C/tp_bdb_fb_pre_tc_04c_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-04C/tp_bdb_fb_pre_tc_04c_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-07/tp_bdb_fb_pre_tc_07_dut_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-07/tp_bdb_fb_pre_tc_07_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_BDB_FB-PRE-TC-07/tp_bdb_fb_pre_tc_07_thr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-01/tp_nwk_bv-01_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-01/tp_nwk_bv-01_dutzr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-01/tp_nwk_bv-01_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-01/tp_nwk_bv-01_gzr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-02/tp_nwk_bv-02_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-02/tp_nwk_bv-02_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zc.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr1.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr2.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr3.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr4.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr5.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr6.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr7.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr8.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr9.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr10.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr11.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr12.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr13.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr14.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr15.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr16.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/tp_nwk_bv-05_zr17.c ${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-05/test_common.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-06-I/tp_nwk_bv-06-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-06-I/tp_nwk_bv-06-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-07-I/tp_nwk_bv-07-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-07-I/tp_nwk_bv-07-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-08-I/tp_nwk_bv-08-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_NWK_BV-08-I/tp_nwk_bv-08-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-1/tp_ped-1_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-1/tp_ped-1_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-10/tp_ped-10_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-10/tp_ped-10_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-11/tp_ped-11_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-11/tp_ped-11_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-12/tp_ped-12_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-12/tp_ped-12_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-13/tp_ped-13_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-13/tp_ped-13_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-14/tp_ped-14_gzr_d.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-14/tp_ped-14_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-14/tp_ped-14_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-14/tp_ped-14_gzr_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-2/tp_ped-2_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-3/tp_ped-3_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-3/tp_ped-3_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-4/tp_ped-4_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-4/tp_ped-4_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-5/tp_ped-5_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-5/tp_ped-5_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-6/tp_ped-6_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-6/tp_ped-6_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-6/tp_ped-6_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-7/tp_ped-7_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-8/tp_ped-8_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PED-9/tp_ped-9_thzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-01/tp_pro_bv_01_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-01/tp_pro_bv_01_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-02/tp_pro_bv_02_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-03/tp_pro_bv_03_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-03/tp_pro_bv_03_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-04/tp_pro_bv_04_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-04/tp_pro_bv_04_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-04/tp_pro_bv_04_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-05/tp_pro_bv-05_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-05/tp_pro_bv-05_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-05/tp_pro_bv-05_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-06/tp_pro_bv_06_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-06/tp_pro_bv_06_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-06/tp_pro_bv_06_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-06/tp_pro_bv_06_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-08/tp_pro_bv_08_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-08/tp_pro_bv_08_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-08/tp_pro_bv_08_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-08/tp_pro_bv_08_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-09/tp_pro_bv_09_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-09/tp_pro_bv_09_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-09/tp_pro_bv_09_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-09/tp_pro_bv_09_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-09/tp_pro_bv_09_zr4.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-10/tp_pro_bv_10_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-10/tp_pro_bv_10_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-10/tp_pro_bv_10_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-11/tp_pro_bv_11_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-11/tp_pro_bv_11_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-11/tp_pro_bv_11_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-11/tp_pro_bv_11_zr4.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-12/tp_pro_bv_12_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-12/tp_pro_bv_12_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-13/tp_pro_bv_13_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-13/tp_pro_bv_13_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-14/tp_pro_bv_14_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-14/tp_pro_bv_14_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-15/tp_pro_bv_15_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-15/tp_pro_bv_15_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-15/tp_pro_bv_15_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-15/tp_pro_bv_15_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-15/tp_pro_bv_15_zr4.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-16/tp_pro_bv_16_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-16/tp_pro_bv_16_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-16/tp_pro_bv_16_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-17/tp_pro_bv_17_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-17/tp_pro_bv_17_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-17/tp_pro_bv_17_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-28/tp_pro_bv_28_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-2930/tp_pro_bv_29_zc1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-2930/tp_pro_bv_29_zc2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-2930/tp_pro_bv_29_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-2930/tp_pro_bv_29_zr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-2930/tp_pro_bv_29_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-31/tp_pro_bv_31_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-31/tp_pro_bv_31_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-31/tp_pro_bv_31_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-32/tp_pro_bv_32_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-32/tp_pro_bv_32_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-36/tr_pro_bv_36_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-36/tr_pro_bv_36_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-37/tp_pro_bv-37_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-37/tp_pro_bv-37_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-39/tp_pro_bv_39_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-39/tp_pro_bv_39_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-40/tp_pro_bv_40_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-40/tp_pro_bv_40_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-40/tp_pro_bv_40_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-42/tp_pro_bv_42_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-42/tp_pro_bv_42_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-42/tp_pro_bv_42_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-43/tp_pro_bv_43_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-43/tp_pro_bv_43_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-43/tp_pro_bv_43_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-44/tp_pro_bv_44_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-44/tp_pro_bv_44_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_PRO_BV-44/tp_pro_bv_44_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-01/tp_r20_bv-01_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-01/tp_r20_bv-01_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-02/tp_r20_bv-02_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-02/tp_r20_bv-02_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-03/tp_r20_bv-03_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-03/tp_r20_bv-03_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-04/tp_r20_bv-04_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-04/tp_r20_bv-04_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-05/tp_r20_bv-05_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-05/tp_r20_bv-05_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-06/tp_r20_bv-06_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-06/tp_r20_bv-06_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-07/tp_r20_bv-07_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-07/tp_r20_bv-07_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-08/tp_r20_bv-08_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-08/tp_r20_bv-08_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-09/tp_r20_bv-09_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-09/tp_r20_bv-09_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-10/tp_r20_bv-10_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-10/tp_r20_bv-10_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-11/tp_r20_bv-11_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-11/tp_r20_bv-11_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-12/tp_r20_bv-12_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-12/tp_r20_bv-12_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-13/tp_r20_bv-13_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-13/tp_r20_bv-13_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-14/tp_r20_bv-14_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-14/tp_r20_bv-14_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-15/tp_r20_bv-15_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R20_BV-15/tp_r20_bv-15_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-01/tp_r21_bv-01_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-01/tp_r21_bv-01_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-01/tp_r21_bv-01_gzr_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-01/tp_r21_bv-01_gzr_d.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-02/tp_r21_bv-02_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-02/tp_r21_bv-02_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-02/tp_r21_bv-02_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-03/tp_r21_bv-03_gzc1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-03/tp_r21_bv-03_gzc2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-03/tp_r21_bv-03_gzc3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-03/tp_r21_bv-03_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-03/tp_r21_bv-03_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-04/tp_r21_bv_04_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-04/tp_r21_bv_04_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-04/tp_r21_bv_04_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-05/tp_r21_bv_05_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-06/tp_r21_bv-06_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-06/tp_r21_bv-06_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-06/tp_r21_bv-06_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-07/tp_r21_bv-07_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-07/tp_r21_bv-07_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-08/tp_r21_bv-08_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-08/tp_r21_bv-08_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-09/tp_r21_bv-09_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-09/tp_r21_bv-09_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-10/tp_r21_bv-10_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-10/tp_r21_bv-10_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-11/tp_r21_bv-11_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-11/tp_r21_bv-11_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-11/tp_r21_bv-11_gzr1_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-11/tp_r21_bv-11_gzr1_d.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-11/tp_r21_bv-11_gzr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-12/tp_r21_bv-12_gzc1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-12/tp_r21_bv-12_gzc2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-12/tp_r21_bv-12_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-13/tp_r21_bv-13_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-13/tp_r21_bv-13_dutzr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-13/tp_r21_bv-13_dutzr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-25/tp_r21_bv-25_gzr_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-25/tp_r21_bv-25_gzr_d.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-25/tp_r21_bv-25_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-25/tp_r21_bv-25_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_gzr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_gzr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-26/tp_r21_bv-26_gzr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-27/tp_r21_bv-27_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-27/tp_r21_bv-27_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-27/tp_r21_bv-27_gzr_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-27/tp_r21_bv-27_gzr_d.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-28/tp_r21_bv-28_gzr_c.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-28/tp_r21_bv-28_gzr_d.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-28/tp_r21_bv-28_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-28/tp_r21_bv-28_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-29/tp_r21_bv-29_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-29/tp_r21_bv-29_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-30/tp_r21_bv-30_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R21_BV-30/tp_r21_bv-30_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R222_10_70/tp_r222_10_70_dut_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R222_10_70/tp_r222_10_70_dut_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R222_10_71/tp_r222_10_71_dut_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-16/tp_r22_bv-16_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-16/tp_r22_bv-16_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-16/tp_r22_bv-16_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-17/tp_r22_bv-17_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-17/tp_r22_bv-17_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-17/tp_r22_bv-17_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-18/tp_r22_bv_18_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-18/tp_r22_bv_18_gzr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-18/tp_r22_bv_18_gzr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_BV-18/tp_r22_bv_18_dutzr3.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2462/tp_r22_ccb-2462_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2462/tp_r22_ccb-2462_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2462/tp_r22_ccb-2462_gzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2469/tp_r22_ccb-2469_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_CCB-2469/tp_r22_ccb-2469_dutzr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-01/tp_r22_sgmb-01_dutzmc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-02/tp_r22_sgmb-02_gzmc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-06/tp_r22_sgmb-06_dutzmc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-06/tp_r22_sgmb-06_gzsr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-07/tp_r22_sgmb-07_gzmc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-07/tp_r22_sgmb-07_dut_zsr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-09/tp_r22_sgmb-09_gzmc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-10/tp_r22_sgmb-10_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_R22_SGMB-10/tp_r22_sgmb-10_dut_r.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-24-I/tp_sec_bv-24-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-24-I/tp_sec_bv-24-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-25-I/tp_sec_bv-25-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-25-I/tp_sec_bv-25-i_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-25-I/tp_sec_bv-25-i_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-26-I/tp_sec_bv-26-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-26-I/tp_sec_bv-26-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-27-I/tp_sec_bv-27-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-27-I/tp_sec_bv-27-i_zr1.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-27-I/tp_sec_bv-27-i_zr2.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-28-I/tp_sec_bv-28-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-28-I/tp_sec_bv-28-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-29-I/tp_sec_bv-29-i_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_SEC_BV-29-I/tp_sec_bv-29-i_zr.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-03/tp_zdo_bv-03_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-04/tp_zdo_bv-04_gzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-09/tp_zdo_bv-09_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-10/tp_zdo_bv-10_dutzc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-11/tp_zdo_bv-11_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/TP_ZDO_BV-12/tp_zdo_bv-12_zc.c
	${ZB_STACK_DIR}/tests/PRO_R22/certification/GPPB_CERT_ROUTER/zr.c
)