# This file is generated automatically by : python menuconfig.py -s ../component/example/ethernet/ethernet_high_tp/prj.conf
CONFIG_ETHERNET=y
CONFIG_IMG2_PSRAM=y
CONFIG_CLKCFG_1P0_RMII_USB=y
CONFIG_HIGH_TP_TEST=y
CONFIG_PBUF_POOL_BUFSIZE=1536
CONFIG_ETH_TX_DESC_CNT=16
