"""
Hand-rendered json5 templates for project_info.json5 / board_info.json5.

We render the file as text (rather than using json5.dumps) because the
json5 library does not preserve comments. All comments use /* */ block
style — never inline `//`.

Auto-generated regions are flagged with a "generated by build, do not
edit" header so users know which sections incremental updates will
overwrite.
"""

from __future__ import annotations

import json
import os
from typing import List, Optional

from ameba_dev_mcp.models.schemas import (
    BoardInfo,
    ProjectInfo,
    ProjectImageEntry,
    ProjectEntry,
)


PROJECT_INFO_FILENAME = "project_info.json5"
BOARD_INFO_FILENAME = "board_info.json5"

# Templates are stored as standalone json5 files under docs/ so users can
# copy-paste from a real file. Loaded once at import time.
_DOCS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs",
)
PROJECT_INFO_TEMPLATE_PATH = os.path.join(_DOCS_DIR, "project_info.template.json5")
BOARD_INFO_TEMPLATE_PATH = os.path.join(_DOCS_DIR, "board_info.template.json5")


def _read_template(path: str) -> str:
    with open(path, encoding="utf-8") as f:
        return f.read()


# ---------------------------------------------------------------------------
# project_info.json5
# ---------------------------------------------------------------------------

EMPTY_PROJECT_INFO = _read_template(PROJECT_INFO_TEMPLATE_PATH)


def _fmt_image_entry(img: ProjectImageEntry, indent: str) -> str:
    """Render one image entry into json5 with a stable key order."""
    parts: List[str] = []
    if img.type is not None:
        parts.append(f'"type": {json.dumps(img.type)}')
    parts.append(f'"path": {json.dumps(img.path)}')
    parts.append(f'"start_addr": {json.dumps(img.start_addr)}')
    if img.end_addr is not None:
        parts.append(f'"end_addr": {json.dumps(img.end_addr)}')
    if img.optional:
        parts.append('"optional": true')
    inner = ", ".join(parts)
    return f"{indent}{{ {inner} }}"


def _fmt_project_entry(soc: str, entry: ProjectEntry, indent: str = "    ") -> str:
    """Render one project entry block."""
    sub = indent + "  "
    sub2 = sub + "  "
    lines: List[str] = []
    lines.append(f'{indent}{json.dumps(soc)}: {{')
    lines.append(f'{sub}"flash_layout_setting_mode": {json.dumps(entry.flash_layout_setting_mode)},')
    lines.append(f'{sub}"build_dir": {json.dumps(entry.build_dir)},')
    if entry.memory_type:
        lines.append(f'{sub}"memory_type": {json.dumps(entry.memory_type)},')

    if entry.flash_layout_setting_mode == "auto":
        lines.append("")
        lines.append(f"{sub}/* === generated by build, do not edit === */")
    if not entry.images:
        lines.append(f'{sub}"images": []')
    else:
        lines.append(f'{sub}"images": [')
        for i, img in enumerate(entry.images):
            tail = "," if i + 1 < len(entry.images) else ""
            lines.append(_fmt_image_entry(img, sub2) + tail)
        lines.append(f"{sub}]")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def render_project_info(model: ProjectInfo) -> str:
    """Render a ProjectInfo back to json5 text with comments."""
    header = (
        "/*\n"
        " * project_info.json5 — flashing-image config for each SoC.\n"
        " *\n"
        " * Two modes per project:\n"
        ' *   - "auto":    images / addresses are filled in by build_firmware.\n'
        " *                Do NOT hand-edit the generated images[] block.\n"
        ' *   - "manual":  user-managed; MCP only validates and never overwrites.\n'
        " *\n"
        " * All paths must be absolute. Address strings must be 0x... hex.\n"
        " * See tools/ameba/ameba_dev_mcp/docs/project_info.md for full schema.\n"
        " */\n"
    )
    body: List[str] = []
    body.append("{")
    body.append(f'  "schema_version": {model.schema_version},')
    body.append("")
    body.append("  /* Global defaults; each project may override. */")
    body.append('  "defaults": {')
    body.append(f'    "memory_type": {json.dumps(model.defaults.memory_type)},')
    body.append(f'    "chip_erase": {json.dumps(model.defaults.chip_erase)}')
    body.append("  },")
    body.append("")
    body.append("  /* Keyed by SoC name (matches build_<SOC>/). */")
    if not model.projects:
        body.append('  "projects": {}')
    else:
        body.append('  "projects": {')
        items = list(model.projects.items())
        for i, (soc, entry) in enumerate(items):
            body.append(_fmt_project_entry(soc, entry, indent="    "))
            if i + 1 < len(items):
                body[-1] += ","
            body.append("")
        if body[-1] == "":
            body.pop()
        body.append("  }")
    body.append("}")
    body.append("")
    return header + "\n".join(body)


# ---------------------------------------------------------------------------
# board_info.json5
# ---------------------------------------------------------------------------

EMPTY_BOARD_INFO = _read_template(BOARD_INFO_TEMPLATE_PATH)


def render_board_info(model: BoardInfo) -> str:
    """Render BoardInfo back to json5. Passwords are NOT masked here —
    this writes back the raw structure to disk; masking happens only for
    MCP resource exposure."""
    header = (
        "/*\n"
        " * board_info.json5 — test-bench config.\n"
        " * See tools/ameba/ameba_dev_mcp/docs/board_info.md for full schema.\n"
        " */\n"
    )
    body: List[str] = []
    body.append("{")
    body.append(f'  "schema_version": {model.schema_version},')
    body.append("")
    body.append('  "defaults": {')
    d = model.defaults
    body.append(f'    "baudrate": {d.baudrate},')
    body.append(f'    "monitor_baudrate": {d.monitor_baudrate},')
    body.append(f'    "chip_erase": {json.dumps(d.chip_erase)}')
    body.append("  },")
    body.append("")
    if model.default_alias is not None:
        body.append(
            "  /* When tools are called without `alias` and 2+ boards are "
            "configured, this one is picked. */"
        )
        body.append(f'  "default_alias": {json.dumps(model.default_alias)},')
        body.append("")
    if not model.boards:
        body.append('  "boards": {}')
    else:
        body.append('  "boards": {')
        items = list(model.boards.items())
        for i, (alias, entry) in enumerate(items):
            sub = "    "
            sub2 = "      "
            kvs: List[str] = []
            kvs.append(f'"soc": {json.dumps(entry.soc)}')
            kvs.append(f'"transport": {json.dumps(entry.transport)}')
            kvs.append(f'"port": {json.dumps(entry.port)}')
            if entry.baudrate is not None:
                kvs.append(f'"baudrate": {entry.baudrate}')
            if entry.monitor_baudrate is not None:
                kvs.append(f'"monitor_baudrate": {entry.monitor_baudrate}')
            if entry.chip_erase is not None:
                kvs.append(f'"chip_erase": {json.dumps(entry.chip_erase)}')
            if entry.add_crlf is not None:
                kvs.append(f'"add_crlf": {json.dumps(entry.add_crlf)}')
            if entry.remote is not None:
                rem = entry.remote
                rline = f'"host": {json.dumps(rem.host)}, "port": {rem.port}'
                if rem.password is not None:
                    rline += f', "password": {json.dumps(rem.password)}'
                kvs.append(f'"remote": {{ {rline} }}')
            if entry.serial_log_record is not None:
                rec = entry.serial_log_record
                rparts = [f'"enable": {json.dumps(rec.enable)}']
                if rec.log_dir is not None:
                    rparts.append(f'"log_dir": {json.dumps(rec.log_dir)}')
                if rec.file_name is not None:
                    rparts.append(f'"file_name": {json.dumps(rec.file_name)}')
                kvs.append(f'"serial_log_record": {{ {", ".join(rparts)} }}')
            body.append(f'{sub}{json.dumps(alias)}: {{')
            for j, kv in enumerate(kvs):
                tail = "," if j + 1 < len(kvs) else ""
                body.append(f"{sub2}{kv}{tail}")
            close = "}," if i + 1 < len(items) else "}"
            body.append(f"{sub}{close}")
        body.append("  }")
    body.append("}")
    body.append("")
    return header + "\n".join(body)
