name: Reusable amebalite workflow template

on:
  workflow_call:
    # parameters from upstream workflow
    inputs:
      module_name:
        required: true
        type: string
      artifacts_name:
        required: true
        type: string
    # parameters from upstream inherit
    secrets:
      TOKEN_AMEBALITE:
        required: false
      TOKEN_AMEBASMART:
        required: false
      TOKEN_AMEBADPLUS:
        required: false

jobs:
  build-template-amebalite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Configure bash
      run: |
        sudo ln -sf /bin/bash /bin/sh

    - name: Install cmake environment variables
      run: |
        sudo apt-get install cmake ninja-build
  
    - name: Configure prerequisites
      run: |
        # set config

        cd amebalite_gcc_project

        if ${{ inputs.artifacts_name == 'amebalite-B1' }}; then
          ./menuconfig.py -f bt1.conf audio_mixer_km4_ap.conf ipc.conf trustzone.conf wifi_all.conf
        fi

        if ${{ inputs.artifacts_name == 'amebalite-B2' }}; then
          ./menuconfig.py -f lite_cross.conf audio_mixer_kr4_ap.conf ipc.conf trustzone.conf
        fi

        if ${{ inputs.artifacts_name == 'amebalite-B3' }}; then
          ./menuconfig.py -f lite_cross.conf audio_passthrough_km4_ap.conf ipc.conf trustzone.conf
        fi

        if ${{ inputs.artifacts_name == 'amebalite-B4' }}; then
          ./menuconfig.py -f lite_cross.conf audio_mixer_kr4_ap.conf bt2.conf ipc.conf trustzone.conf
        fi

        if ${{ inputs.artifacts_name == 'amebalite-B5' }}; then
          ./menuconfig.py -f mp_shrink.conf bt_only.conf
        fi

        if ${{ inputs.artifacts_name == 'amebalite-B6' }}; then
          ./menuconfig.py -f mp_expand.conf bt_only.conf
        fi

        cd -

    - name: Compile
      run: |
        cd amebalite_gcc_project
        ./build.py
        cd -
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifacts_name }}
        path: |
          amebalite_gcc_project/menuconfig/*.config
          amebalite_gcc_project/menuconfig/*.config_kr4
          amebalite_gcc_project/menuconfig/*.config_km4
          amebalite_gcc_project/project_km4/asdk/image
          amebalite_gcc_project/project_kr4/vsdk/image
          amebalite_gcc_project/project_km4/inc
          amebalite_gcc_project/project_kr4/inc